'use client';

/**
 * Existing PDFs Tab
 *
 * Displays previously generated PDFs with version history.
 */

import {
  Box,
  Button,
  CircularProgress,
  Typography,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Chip,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  IconButton,
  Tooltip,
  Alert,
} from '@mui/material';
import {
  PictureAsPdf as PdfIcon,
  Download as DownloadIcon,
  ExpandMore as ExpandMoreIcon,
  Refresh as RefreshIcon,
  History as HistoryIcon,
  Add as AddIcon,
} from '@mui/icons-material';
import type { Timestamp } from 'firebase/firestore';
import type { ExistingPDFsTabProps } from './types';

function formatDate(timestamp: Timestamp) {
  return timestamp.toDate().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

export function ExistingPDFsTab({
  existingPdfs,
  loadingExisting,
  onRefresh,
  onSwitchToGenerate,
}: ExistingPDFsTabProps) {
  const handleDownload = (url: string) => {
    window.open(url, '_blank');
  };

  const latestPdfs = existingPdfs.filter((pdf) => pdf.isLatest);
  const historicalPdfs = existingPdfs.filter((pdf) => !pdf.isLatest);

  if (loadingExisting) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}>
        <CircularProgress />
      </Box>
    );
  }

  if (latestPdfs.length === 0) {
    return (
      <Box sx={{ textAlign: 'center', py: 4 }}>
        <PdfIcon sx={{ fontSize: 48, color: 'text.secondary', mb: 2 }} />
        <Typography color="text.secondary">
          No PDFs have been generated for this RFQ yet.
        </Typography>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={onSwitchToGenerate}
          sx={{ mt: 2 }}
          color="success"
        >
          Generate First PDF
        </Button>
      </Box>
    );
  }

  return (
    <>
      <Box
        sx={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          mb: 2,
        }}
      >
        <Typography variant="subtitle2" color="text.secondary">
          Latest PDFs
        </Typography>
        <Tooltip title="Refresh">
          <IconButton size="small" onClick={onRefresh}>
            <RefreshIcon />
          </IconButton>
        </Tooltip>
      </Box>

      <List disablePadding>
        {latestPdfs.map((pdf) => (
          <ListItem key={pdf.id} disablePadding sx={{ mb: 1 }}>
            <ListItemButton
              onClick={() => handleDownload(pdf.fileUrl)}
              sx={{ borderRadius: 1, border: '1px solid', borderColor: 'divider' }}
            >
              <ListItemIcon>
                <PdfIcon color="error" />
              </ListItemIcon>
              <ListItemText
                primary={pdf.title}
                secondary={
                  <>
                    Version {pdf.version} • Generated by {pdf.uploadedByName}
                    <br />
                    {formatDate(pdf.uploadedAt)}
                  </>
                }
              />
              <Chip label={`v${pdf.version}`} size="small" color="primary" sx={{ mr: 1 }} />
              <DownloadIcon color="primary" />
            </ListItemButton>
          </ListItem>
        ))}
      </List>

      {historicalPdfs.length > 0 && (
        <Accordion sx={{ mt: 2 }}>
          <AccordionSummary expandIcon={<ExpandMoreIcon />}>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
              <HistoryIcon />
              <Typography>Version History ({historicalPdfs.length} older versions)</Typography>
            </Box>
          </AccordionSummary>
          <AccordionDetails>
            <List disablePadding dense>
              {historicalPdfs.map((pdf) => (
                <ListItem key={pdf.id} disablePadding sx={{ mb: 0.5 }}>
                  <ListItemButton
                    onClick={() => handleDownload(pdf.fileUrl)}
                    sx={{ borderRadius: 1, opacity: 0.7 }}
                  >
                    <ListItemIcon>
                      <PdfIcon color="disabled" />
                    </ListItemIcon>
                    <ListItemText
                      primary={pdf.title}
                      secondary={`v${pdf.version} • ${formatDate(pdf.uploadedAt)}`}
                    />
                    <DownloadIcon color="action" />
                  </ListItemButton>
                </ListItem>
              ))}
            </List>
          </AccordionDetails>
        </Accordion>
      )}

      <Alert severity="info" sx={{ mt: 2 }}>
        <Typography variant="body2">
          <strong>Tip:</strong> If you need to regenerate PDFs (e.g., after RFQ changes), switch to
          the &quot;Generate New&quot; tab. Previous versions will be preserved.
        </Typography>
      </Alert>
    </>
  );
}
