// GENERATED by scripts/generate-workflow-guide.mjs — do not edit by hand.
// Source: docs/workflows/user-testing/uat-documents-estimation-materials.md
import type { WorkflowGuideModule } from './types';

export const documentsGuide: WorkflowGuideModule = {
  id: 'documents',
  label: 'Document Control',
  intro: [
    {
      section: 'What this module does',
      blocks: [
        {
          k: 'p',
          text: "**Document control** is how engineering deliverables are tracked on a project: every drawing, calculation and data sheet is registered as a numbered master document, each new version of the file is recorded as a revision and submission, batches of submitted documents are packaged into a numbered transmittal with a cover sheet and a ZIP of the files, and the client's feedback comes back as comments and a Comment Resolution Sheet.",
        },
        {
          k: 'p',
          text: '**Estimation** is where a Bill of Materials (BOM) is built for a piece of equipment — fabricated items priced from a shape and a material, bought-out items priced from the catalog — and turned into a costed quote PDF.',
        },
        {
          k: 'p',
          text: '**The catalogs** are the reference data everything else prices against: the **Material Database** (plates, pipes, valves, fasteners and so on, with their specifications and current prices), **Bought Out Items** (pumps, valves, instruments as procurable equipment), the **Services** rate catalog (engineering, fabrication, testing rates), and the **Shape Database** (the parametric shapes used for weight and cost calculation).',
        },
      ],
    },
    {
      section: 'Before you start',
      blocks: [
        {
          k: 'h',
          text: 'Permissions you need',
        },
        {
          k: 'p',
          text: 'Permissions are set by an administrator in **Administration → Users → Edit User**, where they are grouped by module.',
        },
        {
          k: 'table',
          steps: false,
          head: ['What you want to test', 'Permission needed'],
          rows: [
            [
              "See a project's master document list, transmittals and templates",
              '**View** under **Projects**, and be assigned to the project',
            ],
            [
              'Create documents, import a register, set up numbering, transmittals',
              '**Manage** under **Document Management**',
            ],
            [
              'Submit a revision on a document assigned to you',
              '**Submit** under **Document Management**',
            ],
            ['Approve or reject a comment resolution', '**Manage** under **Projects**'],
            [
              'See BOMs, materials, bought-out items, services, shapes',
              '**View** under **Estimation**',
            ],
            [
              'Create or edit BOMs, materials, bought-out items, services',
              '**Manage** under **Estimation**',
            ],
            ['Delete a bought-out item', '**Edit Entities** (an admin-only permission)'],
            [
              'Upload to the Company Documents registry (sidebar → Documents)',
              '**Manage Users** (the registry treats admins as the only uploaders)',
            ],
          ],
        },
        {
          k: 'p',
          text: 'Two things that catch people out:',
        },
        {
          k: 'ul',
          items: [
            'The sidebar shows **Material Database**, **Bought Out Items**, **Services** and **Shape Database** to everyone, but the data behind them is gated on **View** under **Estimation**. A user without it sees the page shell and empty lists, not a clear "no access" message.',
            'Permission changes take a couple of minutes to reach someone who is already signed in. Have them sign out and back in before reporting a permission problem.',
          ],
        },
        {
          k: 'h',
          text: 'Test data you need first',
        },
        {
          k: 'ul',
          items: [
            '**One project you are assigned to**, with a project code (e.g. `PRJ01`). All master documents, transmittals and CRS work happens inside a project.',
            '**A second, empty project** for UAT-DOC-01 — auto-numbering can only be set up on a project that has no documents yet (see Known issues).',
            '**A file to upload as a drawing** — one PDF and one native file (DWG, XLSX or DOCX), each under 50 MB.',
            '**A file to upload as a CRS** — a PDF, Excel or Word file under 50 MB.',
            '**An Excel file for the register import** — download the template from inside the import dialog in UAT-DOC-04.',
            '**At least three materials with a density and a current price**, so BOM cost calculation produces a non-zero number. Material prices can only be set by accepting a vendor quote price in Procurement (see UAT-MAT-04) — arrange this before you start the estimation tests, or accept that costs will come out as ₹0.',
            '**At least one bought-out item** in the catalog (UAT-MAT-08 creates one).',
          ],
        },
        {
          k: 'h',
          text: 'A second user',
        },
        {
          k: 'p',
          text: 'Several tests need one.',
        },
        {
          k: 'table',
          steps: false,
          head: ['Account', 'What it needs', 'Used by'],
          rows: [
            [
              '**Your account**',
              '**Manage** under Document Management, **Manage** under Estimation, **Manage** under Projects',
              'Everything',
            ],
            [
              '**A limited user**',
              'Assigned to the same project, **View** under Projects only — no **Manage** under Document Management, no **Manage** under Estimation',
              'UAT-DOC-17, UAT-EST-10, UAT-MAT-17',
            ],
            [
              '**A second manager**',
              '**Manage** under Projects, assigned to the project',
              "UAT-DOC-10 (approving someone else's resolution)",
            ],
            ['**An admin**', '**Manage Users** and **Edit Entities**', 'UAT-MAT-11, UAT-DOC-18'],
          ],
        },
        {
          k: 'h',
          text: 'Where things live in the sidebar',
        },
        {
          k: 'ul',
          items: [
            '**SETUP → Documents** — this is the **Company Documents** registry (SOPs, policies, templates). It is **not** the project document control area. Only UAT-DOC-18 tests it.',
            '**Project master documents** are reached from **DAILY OPERATIONS → Projects → open a project → Documents**. Everything from UAT-DOC-01 to UAT-DOC-17 starts there.',
            '**SALES & ESTIMATION → Estimation** — the BOM list.',
            '**ENGINEERING DATA → Material Database**, **Bought Out Items**, **Services**, **Shape Database**.',
          ],
        },
        {
          k: 'p',
          text: '**Read [Known issues in this module](#known-issues-in-this-module) at the bottom before you start.** Twenty-two things in this module are already known to be broken or missing. Do not spend time filing them again.',
        },
      ],
    },
  ],
  workflows: [
    {
      id: 'UAT-DOC-01',
      title: 'Set up document auto-numbering on a project',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'the project can allocate document numbers on its own, in the format your engineers expect.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** under **Document Management**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'A project **with no documents in it yet**. If the project already has one document, the setup banner is gone and there is no other way in — use a fresh project.',
          ],
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Go to **Projects**, open the empty project, and click the **Documents** card',
              'The **Document Management** page, with the project name and code under the title, and tabs **Master Document List**, **Transmittals**, **Templates**',
            ],
            [
              '2',
              'Stay on **Master Document List**',
              'A blue tip panel offering **Set Up Auto-Numbering** and **Upload Document Register**, with a note that numbers will look like `{your project code}-01-001`',
            ],
            [
              '3',
              'Click **Set Up Auto-Numbering**',
              'Dialog **Set Up Document Numbering**, explaining numbers will be `{PROJECTCODE}-[DISCIPLINE]-[SEQ]`',
            ],
            [
              '4',
              'Read the discipline list',
              'Eleven disciplines, all ticked: 00 Client Inputs, 01 Process, 02 Mechanical, 03 Structural, 04 Piping, 05 Electrical, 06 Instrumentation, 07 Civil, 08 HVAC, 09 Automation, 10 Safety',
            ],
            ['5', 'Click **Deselect All**', 'Every tick clears, and the confirm button greys out'],
            [
              '6',
              'Tick **01 — Process**, **02 — Mechanical** and **04 — Piping** only',
              'The confirm button now reads **Initialize 3 Disciplines**',
            ],
            [
              '7',
              'Click **Initialize 3 Disciplines**',
              'The button shows **Initializing...**, then the dialog closes and the tip panel disappears',
            ],
            ['8', 'Reload the page', 'The tip panel stays gone — the setting stuck'],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Re-open the same project a day later and confirm the numbering is still in place — the counters are stored per project, not per browser.',
            'Repeat step 3 on a *second* empty project and use **Select All** instead. All eleven disciplines should be accepted.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: ['Confirming with no disciplines ticked — the button must stay disabled.'],
        },
      ],
    },
    {
      id: 'UAT-DOC-02',
      title: 'Register a master document and check the number format',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'a numbered engineering deliverable exists on the project and starts life correctly.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** under **Document Management**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'the project from **UAT-DOC-01**, with numbering set up.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'On **Master Document List**, click **New Document**',
              'Dialog **Create New Master Document**',
            ],
            [
              '2',
              'Pick **01 - Process** in **Discipline**',
              'A blue line at the top updates to read **Document Number: {PROJECTCODE}-01-001**',
            ],
            [
              '3',
              'Type `Process Flow Diagram — Unit 1` into **Document Title**',
              'The field accepts it',
            ],
            [
              '4',
              'Choose **Drawing** in **Document Type**',
              'The list offers Drawing, Calculation, Specification, Data Sheet, Report, Manual, Procedure, Schedule, List, General — and you can also type your own',
            ],
            [
              '5',
              'Leave **Client Visible** switched off',
              'The caption under it reads *Document is internal only*',
            ],
            [
              '6',
              'Click **Create Document**',
              'Button shows **Creating...**, the dialog closes, and a new row appears in the list',
            ],
            [
              '7',
              'Read the new row',
              'Doc Number `{PROJECTCODE}-01-001`, your title, Type `Drawing`, **Rev** `R0`, **Status** showing DRAFT',
            ],
            [
              '8',
              'Create a second Process document called `P&ID — Unit 1`',
              'Its number is `{PROJECTCODE}-01-002` — the sequence advanced by one',
            ],
            [
              '9',
              'Create a third document, this time under discipline **02 - Mechanical**',
              'Its number is `{PROJECTCODE}-02-001` — each discipline counts separately',
            ],
            [
              '10',
              'Create a fourth under **00 - Client Inputs** and choose sub-code **A - Process Data**',
              'The preview and the created number include the sub-code: `{PROJECTCODE}-00-A-001`',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Every new document starts at revision **R0**, status DRAFT, with no submissions recorded.',
            'On a project where numbering was never set up, the same dialog shows a free-text **Document Number** field instead of the discipline preview, with the helper *"Enter the document number manually…"*.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Creating a document with an empty title — the dialog must show **Title is required** and not save.',
            'Creating a document with no discipline chosen — **Discipline code is required**.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-03',
      title: 'Master document round-trip: nothing lost between save and reopen',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'every field you fill on the create form is still there when you reopen the document for editing. This is the single most common defect in this app — check it carefully.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** under **Document Management**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'the project from UAT-DOC-01, with at least two team members assigned to it.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Click **New Document** and fill **every** field: Discipline `04 - Piping`, Title `Piping GA — North Rack`, Description `Full round-trip test`, Document Type `Specification`, **Client Visible** switched **on**, **Assign To** two team members, **Due Date** a date two weeks out',
              'Every field accepts input; the caption under the switch changes to *Document is visible to client*',
            ],
            ['2', 'Write down every value you entered', '—'],
            [
              '3',
              'Click **Create Document**',
              'The document appears in the list with number `{PROJECTCODE}-04-001`',
            ],
            [
              '4',
              'Click the row to open the document',
              'The detail page, headed with the document number, a status chip, a **Client Visible** chip, the title, and chips for Discipline and Revision',
            ],
            [
              '5',
              'On the **Overview** tab, compare every field against your notes',
              'Document Number, Title, Description, Discipline Code, Document Type, Current Revision `R0`, Status, Visibility *Client Visible*, Due Date and both assignees all match',
            ],
            [
              '6',
              'Click **Edit**',
              'Dialog **Edit Document**, with the document number shown under the title',
            ],
            [
              '7',
              'Compare every field in the edit dialog against your notes',
              'Title, Discipline, Description, Due Date and the **Client Visible** switch are all pre-filled with what you entered — nothing is blank, nothing reset',
            ],
            [
              '8',
              'Without changing anything, click **Save Changes**',
              'The dialog closes and the page refreshes',
            ],
            [
              '9',
              'Re-open **Edit** and check every field again',
              'Identical to step 7 — a save with no edits must not lose anything',
            ],
            [
              '10',
              'Now change the Description, set **Priority** to **High**, move the Due Date a week later, and save',
              'The Overview tab reflects the new description and due date',
            ],
            [
              '11',
              'Re-open **Edit**',
              'Priority still shows **High**, description and date show the new values',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'The assignee list on Overview should still name both team members after step 8. If it empties on save, that is a defect worth reporting.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Saving with an empty title — the dialog must show **Document title is required**.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-04',
      title: 'Import a document register from Excel',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'a whole document register can be loaded in one go instead of typed in one at a time.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** under **Document Management**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'a project (numbering set up or not — import works either way).',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'On **Master Document List**, click **Import Register**',
              'Dialog **Import Document Register**, listing the required columns: A Document Number, B Document Title, C Discipline Code, D Document Type, E Description',
            ],
            [
              '2',
              'Click **Download Template**',
              'An Excel file downloads, named after the project code',
            ],
            [
              '3',
              'Fill the template with five rows, giving each a unique document number and title',
              '—',
            ],
            [
              '4',
              "Deliberately blank the title on row 3, and copy an existing document's number into row 5",
              '—',
            ],
            [
              '5',
              'Drop the file into the upload area and click **Parse File**',
              'A preview table appears headed **Parsed Rows (5 total, 3 valid)**, with per-row chips **Valid**, **Invalid** and **Duplicate**',
            ],
            [
              '6',
              'Read the warning above the table',
              'A yellow panel naming the duplicate document number and saying it will be skipped',
            ],
            [
              '7',
              'Click **Import 3 Documents**',
              'A progress message, then a green line: **Import completed: 3 documents created**',
            ],
            [
              '8',
              'Click **Done** and look at the list',
              'Three new rows, each at revision **R0** and status DRAFT',
            ],
            [
              '9',
              'Repeat the import with the same file',
              'All rows now flag as **Duplicate** and the import button offers nothing to import',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Try uploading a `.txt` file — you should get **Please upload an Excel file (.xlsx or .xls)**.',
            'Try a file over 10 MB — you should get **File size exceeds 10MB limit**.',
            'A row with a document number but no title must be flagged **Invalid**, not silently imported.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: ['Importing while zero rows are valid — the import button must be disabled.'],
        },
      ],
    },
    {
      id: 'UAT-DOC-05',
      title: 'Work the master document list: search, filter, group, export',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'an engineer can find the document they need in a register of hundreds.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone assigned to the project with **View** under **Projects**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'the documents created in UAT-DOC-02 and UAT-DOC-04 (at least eight, across two or more disciplines).',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Look at the cards above the table',
              '**Total Documents**, **Overdue**, **In Review** and **Completed**, with counts that match what you have',
            ],
            [
              '2',
              'Click the **In Review** card',
              'The table filters to documents under review (probably none yet — an empty result is a pass)',
            ],
            [
              '3',
              'Clear it, then click the **My Documents** chip',
              'Only documents assigned to you remain',
            ],
            [
              '4',
              'Clear it and type part of a document title into the search box',
              'The table narrows as you type; searching by document number works too',
            ],
            [
              '5',
              'Set **Status** to **Draft**',
              'Only DRAFT documents remain, and the count chip beside the heading drops to match',
            ],
            ['6', 'Set **Discipline** to `01 - Process`', 'Only Process documents remain'],
            [
              '7',
              'Click **Clear** on the filter bar',
              'All filters reset and every document reappears',
            ],
            [
              '8',
              'Switch the view toggle to the grouped view',
              'Documents group under discipline headings, each with a *"n documents"* chip, and extra columns Due Date and Subs.',
            ],
            [
              '9',
              'Collapse and re-expand a discipline group',
              'The group folds away and comes back with the same rows',
            ],
            [
              '10',
              'Switch back to the flat view and click the download icon (**Export CSV**)',
              'A CSV downloads containing every row currently shown',
            ],
            [
              '11',
              'Add enough documents to exceed 25, then use the pagination control',
              'Page 2 shows the remainder; the 50 and 100 per-page options work',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Status chip text is inconsistent across screens — the list shows `DRAFT` / `IN PROGRESS` while the document detail page shows `DRAFT` / `IN_PROGRESS` with an underscore. This is a known issue; do not file it.',
            "In the grouped view, the **Submit** icon on a row lands you on the document's Overview tab rather than a submission screen. Known issue.",
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-06',
      title: 'Submit the first revision and watch the document go to Submitted',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: "a drawing file is attached to its master document as a numbered, dated submission, and the document's status and revision move on.",
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'the person assigned to the document, with **Submit** under **Document Management** (or **Manage**).',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'The document `{PROJECTCODE}-01-001` from UAT-DOC-02, at revision **R0** and status DRAFT.',
            'One PDF and one native file (DWG/XLSX/DOCX) on your machine.',
          ],
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Open the document and click the **Revisions** tab',
              'Heading **Revisions & Submissions** and the message *"No submissions yet. Upload your first revision to get started."*',
            ],
            [
              '2',
              'Click **Submit New Revision**',
              'Dialog **Submit New Revision — {document number}**',
            ],
            [
              '3',
              'Read the **Revision** field',
              'Pre-filled with **R1**, and a helper line reading *Current revision: R0*',
            ],
            [
              '4',
              'Under **PDF Files**, click **Add Files** and choose your PDF',
              'The filename appears in the PDF section',
            ],
            [
              '5',
              'Under **Native Files (DWG, XLSX, DOCX, etc.)**, add your native file',
              'The filename appears in the native section',
            ],
            [
              '6',
              'Pick yourself in **Submitted By** and type a note in **Submission Notes**',
              'Both accept input',
            ],
            [
              '7',
              'Click **Submit Revision**',
              'An upload progress line counting the files, then the dialog closes',
            ],
            [
              '8',
              'Look at the Revisions tab',
              "One submission card, showing chip **R1**, **#1**, your name, today's date, your note, and a **Pending** chip on the right",
            ],
            [
              '9',
              'Look at the file rows inside the card',
              'Two rows, chipped `PDF` and `NATIVE`, each with a filename, a size and a download button',
            ],
            [
              '10',
              "Click a file's download button",
              'The file downloads and opens correctly — same content you uploaded',
            ],
            [
              '11',
              'Go back to the document header',
              'The revision chip now reads **Revision: R1** and the status chip reads SUBMITTED',
            ],
            [
              '12',
              "Go back to the project's **Master Document List**",
              'The row for this document shows Rev **R1** and status SUBMITTED',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            "The **Overview** tab's **Submission Information** card should now show **Total Submissions: 1** and a last-submission date.",
            'The client-review chip on the submission card (**Pending**) is display-only — there is no control anywhere to change it. Known issue.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Submitting with no files attached — **Submit Revision** must stay disabled.',
            'Submitting with the revision box cleared — **Submit Revision** must stay disabled.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-07',
      title: 'Submit a second revision: revision and submission numbers advance',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'repeated issues of the same drawing are tracked in order, with the newest one on top.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'as UAT-DOC-06.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'the document from **UAT-DOC-06**, at revision **R1** with one submission.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              "Open the document's **Revisions** tab and click **Submit New Revision**",
              'The **Revision** field is pre-filled with **R2**, helper *Current revision: R1*',
            ],
            ['2', 'Attach a different PDF and submit', 'The dialog closes'],
            [
              '3',
              'Read the Revisions tab',
              'Two submission cards. The new one shows **R2** and **#2**; the old one still shows **R1** and **#1**',
            ],
            ['4', 'Check the card order', 'The newest submission is listed first'],
            ['5', 'Check the document header', '**Revision: R2**'],
            [
              '6',
              "Open the R1 card's file and the R2 card's file",
              'Each downloads the file that was uploaded with that revision — the older file is still retrievable',
            ],
            [
              '7',
              'Overwrite the suggested revision with `R2A` and submit again',
              'A third card appears labelled **R2A**, **#3**; the header now reads **Revision: R2A**',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Submission numbers must never repeat or go backwards within a document: #1, #2, #3.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-08',
      title: 'Walk a document through its full status path to Accepted',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'the status of a deliverable reflects where it actually is, and the app only offers the next steps that make sense.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** under **Document Management** (Approved and Accepted need it).',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'a freshly created document in status DRAFT, with no submissions. Create one via UAT-DOC-02 if needed.',
        },
        {
          k: 'p',
          text: "Status is changed from the **Edit** dialog's **Status** dropdown — there is no separate status button. The dropdown only offers the current status plus the steps allowed from it.",
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Open the document, click **Edit**, and open the **Status** dropdown',
              'Four choices: **Draft** (marked *current*), **In Progress**, **On Hold**, **Cancelled** — and nothing else',
            ],
            [
              '2',
              'Choose **In Progress** and click **Save Changes**',
              'The header status chip changes to IN PROGRESS',
            ],
            [
              '3',
              'Re-open **Edit** and open the dropdown',
              '**In Progress** (current), **Submitted**, **On Hold**, **Cancelled**',
            ],
            ['4', 'Choose **Submitted** and save', 'Header shows SUBMITTED'],
            [
              '5',
              'Re-open **Edit** and open the dropdown',
              '**Submitted** (current), **Under Review**, **In Progress** — you can send it back but you cannot jump to Approved',
            ],
            ['6', 'Choose **Under Review** and save', 'Header shows UNDER REVIEW'],
            [
              '7',
              'Re-open **Edit** and open the dropdown',
              '**Under Review** (current), **Approved**, **In Progress**, **On Hold**',
            ],
            ['8', 'Choose **Approved** and save', 'Header shows APPROVED'],
            [
              '9',
              'Re-open **Edit** and open the dropdown',
              '**Approved** (current), **Accepted**, **Under Review**',
            ],
            [
              '10',
              'Choose **Accepted** and save. **This is the end of the line — an Accepted document cannot be moved again.**',
              'Header shows ACCEPTED',
            ],
            [
              '11',
              'Re-open **Edit** and open the dropdown',
              '**Accepted** is the only option in the list',
            ],
            [
              '12',
              'Go back to the **Master Document List** and find the row',
              "Its status column matches, and the row's **Delete** action is greyed out",
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Take a second document from UNDER REVIEW **back** to **In Progress** and confirm it lands there — rework must be possible.',
            'Take a third document from APPROVED back to **Under Review** and confirm it lands there.',
            'On the **Revisions** tab of an Approved or Accepted document, **Submit New Revision** must be greyed out.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Jumping straight from Draft to Approved, or from Submitted to Accepted — those options must not appear in the dropdown at all.',
            'Changing the status of an Accepted document.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-09',
      title: 'On Hold and Cancelled: the side paths and the two terminal states',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'work that is paused or abandoned can be marked as such, and abandoned work stays abandoned.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** under **Document Management**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'three spare documents in status DRAFT.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Open document A, **Edit**, set **Status** to **On Hold**, save',
              'Header shows ON HOLD',
            ],
            [
              '2',
              'Re-open **Edit** and open the dropdown',
              '**On Hold** (current), **Draft**, **In Progress**, **Cancelled**',
            ],
            [
              '3',
              'Set it back to **Draft** and save',
              'Header shows DRAFT — a hold can be released back to the beginning',
            ],
            [
              '4',
              'Put it On Hold again, then set it to **In Progress** and save',
              'Header shows IN PROGRESS — a hold can also be released straight into active work',
            ],
            [
              '5',
              'Take document B to **In Progress**, then **On Hold**, then **Under Review**',
              'The dropdown from On Hold has no **Under Review** option — this step should be impossible',
            ],
            [
              '6',
              'Take document B from **On Hold** to **Cancelled** and save',
              'Header shows CANCELLED',
            ],
            ['7', 'Re-open **Edit** and open the dropdown', '**Cancelled** is the only option'],
            [
              '8',
              'Take document C from **Draft** straight to **Cancelled**',
              'Header shows CANCELLED — cancelling from Draft is allowed',
            ],
            ['9', 'Take a fourth document to **In Progress**, then **Cancelled**', 'Allowed'],
            [
              '10',
              'On the master list, look at the rows for the cancelled documents',
              'Their **Delete** action is greyed out',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Bringing a Cancelled document back to life.',
            'Cancelling a document that is already Submitted, Under Review, Approved or Accepted — Cancelled must not appear in the dropdown for those.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-10',
      title: 'Raise comments and resolve them',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'client feedback on a drawing is recorded, answered, and signed off.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you (raise and resolve) plus a second person with **Manage** under **Projects** (approve).',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'the document from **UAT-DOC-07**, with at least one submission on it. Comments cannot be added to a document that has never been submitted.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Open the document and click the **Comments** tab',
              'Heading **Comments & Resolution**, and a panel saying no comments have been added yet',
            ],
            [
              '2',
              'Click **Add Comment**',
              'Dialog **Add Comment**, showing the document number and title',
            ],
            [
              '3',
              'Fill **Comment Text**, set **Severity** to **Major**, **Category** to **Technical**, and fill **Page Number**, **Section** and **Line Item**',
              'All fields accept input, and a chip echoes the chosen severity',
            ],
            [
              '4',
              'Click **Add Comment**',
              'The dialog closes and a row appears in the comments table',
            ],
            [
              '5',
              'Read the row',
              "A comment number, severity `MAJOR`, your text, category, the location as *Page n · §x · Item y*, status **OPEN**, today's date",
            ],
            [
              '6',
              'Read the subtitle under the heading',
              'A tally: *1 total comment(s) • 1 open • 0 under review • 0 resolved • 0 closed*',
            ],
            [
              '7',
              'Add three more comments with severities **Critical**, **Minor** and **Suggestion**',
              'Four rows; the tally updates to 4 total, 4 open',
            ],
            [
              '8',
              'Click the **Open** filter, then **All**',
              'The table filters and unfilters correctly, and each filter button shows a count',
            ],
            [
              '9',
              'Click the **Respond** action on the first comment',
              'Dialog **Comment {number}** with the original text, its location, and a **Provide Resolution** section',
            ],
            [
              '10',
              'Type a resolution into **Resolution Response** and click **Submit Resolution**',
              "The dialog closes; the comment's status changes to **RESOLVED** and the tally moves one from open to resolved",
            ],
            [
              '11',
              '**As the second manager**, sign in, open the same comment via **View Thread**',
              'A **Project Manager Review** section with **PM Remarks (Optional)**, and buttons **Reject** and **Approve**',
            ],
            ['12', 'Click **Approve**', 'The comment gains a **PM Approved** chip'],
            [
              '13',
              'Resolve a second comment, then as the second manager type a reason and click **Reject**',
              'The comment goes back to **OPEN** so it can be answered again',
            ],
            [
              '14',
              'Back on the Comments tab, click **Export CRT**',
              'A comment file downloads listing every comment with its severity, status and resolution',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: ['The **Refresh** button reloads the list without losing your filter.'],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Submitting an empty resolution — you should get **Please enter a resolution response**.',
            'Rejecting a resolution with no remarks — you should get a message asking for a reason.',
            'Adding a comment on a document that has never been submitted — the dialog warns you to submit the document first and refuses to save.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-11',
      title: 'Upload a Comment Resolution Sheet',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: "the client's marked-up comment sheet is filed against the right revision, and the document moves into review on its own.",
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** or **Submit** under **Document Management**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'the document from UAT-DOC-07 with at least one submission, and a CRS file (PDF, Excel or Word, under 50 MB).',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              "Note the document's current status from the header",
              'Write it down — you will compare after upload',
            ],
            [
              '2',
              'On the **Comments** tab, click **Upload CRS**',
              'Dialog **Upload Comment Resolution Sheet**, showing the document number and title',
            ],
            [
              '3',
              'Click **Select File** and choose your CRS file',
              'The filename, size and a **Remove** button appear; **Select Submission** auto-picks the latest revision',
            ],
            [
              '4',
              'Open **Select Submission**',
              'Every submission on this document is listed with its revision and submission number',
            ],
            [
              '5',
              'Leave the latest selected and click **Upload**',
              'An upload progress line, then the dialog closes',
            ],
            [
              '6',
              'Look above the comments table',
              'A section **Uploaded Comment Resolution Sheets (1)** with your filename, its revision chip, size, your name, the date, and a **Pending** chip',
            ],
            [
              '7',
              'Click **Open File**, then **Download**',
              'The file opens in a new tab and downloads correctly',
            ],
            [
              '8',
              'Look at the document header',
              'The status has moved to UNDER REVIEW on its own — this is automatic, there is no button for it',
            ],
            [
              '9',
              'Type the comments from your CRS in via **Add Comment** (as in UAT-DOC-10)',
              'Each appears in the table',
            ],
            [
              '10',
              'Look for a way to mark the CRS as processed or complete',
              '⚠ known issue — there is none. The CRS chip stays on **Pending** forever. Do not report this',
            ],
            [
              '11',
              'Upload a second CRS against the same submission',
              'The section header becomes **Uploaded Comment Resolution Sheets (2)** and both files are listed',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'The **Notes (Optional)** box on the upload dialog is not saved anywhere. Known issue; do not report it.',
            "If the document's status does not permit a move to Under Review (for example it is Accepted), the upload still succeeds and the status simply stays where it was. That is correct behaviour.",
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Uploading a file over 50 MB — you should get **File size exceeds 50MB limit**.',
            'Uploading an image or a ZIP — you should get **Please upload a PDF, Excel, or Word document**.',
            'Clicking **Upload** before choosing a file and a submission — the button must stay disabled.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-12',
      title: 'Generate a transmittal and download its PDF and ZIP',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'a batch of submitted drawings is issued to the client as one numbered transmittal, with a cover sheet and a single ZIP of the files.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** under **Document Management**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'At least **three documents with at least one submission each** (repeat UAT-DOC-06 on two more documents). Documents with no submission will not appear for selection.',
          ],
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'On the project, open the **Transmittals** tab',
              'Heading **Document Transmittals** and a **Generate Transmittal** button',
            ],
            [
              '2',
              'Click **Generate Transmittal**',
              'Dialog **Generate Document Transmittal**, with the steps **Select Documents → Transmittal Details → Preview & Generate**',
            ],
            [
              '3',
              'Read the note at the top of step 1',
              'It says only documents with at least one submission are shown',
            ],
            [
              '4',
              'Tick two documents',
              'The summary reads *2 of n documents selected* and **Next** becomes clickable',
            ],
            [
              '5',
              'Type into **Search** and confirm the list narrows, then clear it',
              'Filtering by document number and by title both work',
            ],
            ['6', 'Click **Next**', 'Step 2 — **Transmittal Details**'],
            [
              '7',
              'Fill **Subject**, **Purpose of Issue**, set **Delivery Method** to **Both Hard & Soft Copy**, and write **Cover Notes**',
              'All fields accept input; the footnote confirms the number and date are generated for you',
            ],
            [
              '8',
              'Click **Next**',
              'Step 3 — a **Transmittal Summary** repeating everything you entered, plus a **Documents to be Transmitted** table',
            ],
            [
              '9',
              'Check the summary against what you typed',
              'Subject, Purpose of Issue, Cover Notes and the document count all match',
            ],
            [
              '10',
              'Click **Generate & Download**. **This creates a permanent numbered transmittal record.**',
              'The button shows **Generating...**, then a PDF and a ZIP download',
            ],
            [
              '11',
              'Open the PDF',
              'A transmittal cover sheet showing the transmittal number, the date, your subject, purpose of issue, cover notes and the list of documents with their revisions',
            ],
            [
              '12',
              'Check the transmittal number on the PDF',
              'It reads **TR-001** (three digits, counting up per project)',
            ],
            [
              '13',
              'Open the ZIP',
              'It contains the cover sheet PDF plus one file per included document',
            ],
            [
              '14',
              'Look at the **Transmittals History** list on the page',
              "A row for **TR-001** with today's date, your subject, the document count, status **GENERATED** and your name",
            ],
            [
              '15',
              'Go back to the **Master Document List**',
              'The documents you included are at status SUBMITTED',
            ],
            ['16', 'Generate a second transmittal with one document', 'Its number is **TR-002**'],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            "The **Client** field on the generated transmittal reads the literal text *Client Name* rather than your customer's name. Known issue; do not report it.",
            'The **Status** filter on step 1 includes an option **Client Review** that always returns zero documents. Known issue.',
            'The ZIP contains one file per document, not both the native and the PDF file. Known issue.',
            '**Delivery Method** decides which files go into the ZIP: *Hard Copy Only* takes PDFs, *Soft Copy Only* takes native files, *Both* takes everything. Generate one of each and confirm the ZIP contents differ.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Clicking **Next** on step 1 with nothing selected — the button must stay disabled and the helper text tells you to select at least one document.',
            'Clicking **Generate Transmittal** on a project with no documents — the button must be greyed out.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-13',
      title: 'Transmittal history: view, re-download, regenerate, delete',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'a transmittal issued last month can still be opened and re-sent, and a mistake can be removed.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** under **Document Management**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'the two transmittals from **UAT-DOC-12**.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'On the **Transmittals** tab, type `TR-001` into the search box',
              'Only that transmittal remains; searching by subject or by your name works too',
            ],
            [
              '2',
              'Click **View Details** on TR-001',
              'Dialog **Transmittal Details** with the number as a subtitle and a status chip reading GENERATED',
            ],
            [
              '3',
              'Read the **Transmittal Information** section',
              'Project, Client, Transmittal Date, Documents count, Subject, Purpose of Issue and Cover Notes — all matching what you entered',
            ],
            [
              '4',
              'Read the **Files** section',
              'A row for the transmittal PDF and a row for the complete package ZIP with its size, each with a **Download** button',
            ],
            ['5', 'Click **Download** on the PDF row', 'The same cover sheet downloads again'],
            ['6', 'Click **Download ZIP** at the bottom of the dialog', 'The ZIP downloads again'],
            [
              '7',
              'Read the **Documents Included** table',
              'Every document with its number, title, revision and status',
            ],
            [
              '8',
              'Close the dialog and click the **Regenerate** action on TR-001',
              'A message *"Regenerating transmittal…"*, then a fresh PDF and ZIP download and a green toast **TR-001 regenerated and downloaded**',
            ],
            [
              '9',
              'Confirm the transmittal number after regenerating',
              'Still **TR-001** — regenerating must not consume a new number',
            ],
            [
              '10',
              'Click **Delete** on TR-002',
              'Dialog **Delete Transmittal** warning it cannot be undone',
            ],
            ['11', 'Confirm the delete', 'Toast **TR-002 deleted** and the row disappears'],
            [
              '12',
              'Generate a new transmittal',
              'Its number is **TR-003** — numbers are never reused',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'The empty transmittal table tells you to click *"Create Transmittal"*, but the button is labelled **Generate Transmittal**. Known issue.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Downloading the ZIP for a transmittal that has none — you should get a clear error, **ZIP file not available for this transmittal**, not a broken download.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-14',
      title: 'Mark a transmittal Sent and Acknowledged',
      knownIssue: true,
      blocks: [
        {
          k: 'note',
          text: '⚠ **Known issue — expected to fail.** A transmittal is supposed to progress from Generated to **Sent** (when you post or email it) and then to **Acknowledged** (when the client confirms receipt). Neither step has a button in the app, so no transmittal can ever leave the **GENERATED** status. Do not file feedback for this; it is already on the fix list.',
          warn: true,
        },
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the two missing steps are genuinely missing, so nobody assumes they are hidden somewhere.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** under **Document Management**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'the transmittal TR-001 from UAT-DOC-12, at status GENERATED.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'On the **Transmittals** tab, look at the row actions for TR-001',
              'Only **View Details**, **Download ZIP**, **Regenerate** and **Delete** — ⚠ no Send, no Acknowledge',
            ],
            [
              '2',
              'Open **View Details** and look at the bottom of the dialog',
              'Only **Close** and **Download ZIP** — ⚠ no Mark as Sent, no Acknowledge',
            ],
            [
              '3',
              'Confirm the status chip',
              '⚠ Stays **GENERATED**, and nothing in the app can move it',
            ],
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-15',
      title: 'Document templates: upload and download',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'the project team can pull a standard drawing or report template instead of starting from scratch.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage** under **Document Management**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'a template file (Excel, Word or CAD) under 50 MB.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'On the project, open the **Templates** tab',
              'Heading **Document Templates**, subtitle *"Company-wide and project-specific templates"*',
            ],
            ['2', 'Click **Upload Template**', 'Dialog **Upload Document Template**'],
            [
              '3',
              'Select your file',
              'The filename appears and **Template Name** fills itself from the filename',
            ],
            [
              '4',
              'Change the name, add a **Description**, set **Category** to **Calculation** and **Scope** to **This Project Only**, and fill **Usage Instructions (Optional)**',
              'Every field accepts input',
            ],
            ['5', 'Click **Upload Template**', 'A progress percentage, then the dialog closes'],
            [
              '6',
              'Read the new row',
              'Columns Template, Category, Scope (`PROJECT SPECIFIC`), File, Version (`v1`), Downloads, Updated, Actions',
            ],
            [
              '7',
              'Click **Download** on the row',
              'The template downloads, identical to what you uploaded, and the Downloads count goes up',
            ],
            [
              '8',
              'Upload a second template with **Scope** set to **Company Wide**',
              'It appears with scope `COMPANY WIDE`',
            ],
            [
              '9',
              'Use the **Category** filter and the search box',
              'Both narrow the list correctly; the category chips above the table also filter when clicked',
            ],
            [
              '10',
              "Open another project's **Templates** tab",
              'The company-wide template appears there too; the project-specific one does not',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Uploading a file over 50 MB — **File size exceeds 50MB limit**.',
            'Uploading with the name cleared — **Template name is required**, and the button stays disabled.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-16',
      title: 'Document Links, Supply List and Work List',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'a document records what must be finished before it can start, what it depends on, and what material and labour it carries.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone assigned to the project.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'at least three master documents on the project.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Open a document and click the **Document Links** tab',
              'Heading **Document Links & Dependencies** with sections **Predecessors**, **Successors** and **Related Documents**, each currently empty with an explanatory line',
            ],
            [
              '2',
              'Add another document as a predecessor',
              'It appears under **Predecessors**, and the summary line reads *Predecessors Status: 0 of 1 completed*',
            ],
            [
              '3',
              'Take that predecessor document to status **Accepted** (UAT-DOC-08), then come back',
              'The summary reads *1 of 1 completed* and tells you the document is ready to start',
            ],
            [
              '4',
              "Open the predecessor document's own **Document Links** tab",
              'Your first document is listed under **Successors**, and the summary warns that one document depends on it',
            ],
            [
              '5',
              'Click the **Supply List** tab',
              'Heading **Supply List** with an item count and a total estimated cost, plus **Refresh** and **Add Supply Item**',
            ],
            [
              '6',
              'Add a supply item with a name, quantity and estimated cost',
              'The row appears and the total at the top of the tab increases by the amount you entered',
            ],
            [
              '7',
              'Delete the supply item',
              'A confirmation naming the item, and after confirming the row goes and the total drops back',
            ],
            [
              '8',
              'Click the **Work List** tab',
              'Heading **Work List** with an item count and an estimated hours total',
            ],
            [
              '9',
              'Add a work item with estimated hours',
              'The row appears and the hours total increases',
            ],
            [
              '10',
              'Return to the **Overview** tab',
              'The **Linked Items** card shows the Supply Items, Work Items and Document Links counts you just created',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'The "view" action on a supply item shows an information message saying the detail view is coming soon. That is expected, not a defect.',
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-17',
      title: 'Document control permission checks',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'someone who should only read the register cannot change it.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you, plus a limited user assigned to the same project with **View** under **Projects** and **no** Document Management permissions.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'the project with documents and at least one transmittal.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              "**As the limited user**, sign in and open the project's **Documents** page",
              'The Master Document List loads and the documents are readable',
            ],
            [
              '2',
              'Look at the action bar',
              '**New Document** and **Import Register** are not shown at all',
            ],
            ['3', "Look at a document row's actions", 'Only **View Details** — no Edit, no Delete'],
            [
              '4',
              'Open the **Transmittals** tab',
              'The history is readable but **Generate Transmittal** is not shown',
            ],
            [
              '5',
              'Open the **Templates** tab',
              'Templates are downloadable but **Upload Template** is not shown',
            ],
            [
              '6',
              'Open a document and try to click **Edit** in the header',
              'Either the button is absent, or clicking through and saving is refused with a permissions message rather than silently succeeding',
            ],
            [
              '7',
              '**As yourself**, remove the limited user from the project team, then have them retry step 1',
              "They should no longer be able to see the project's documents at all",
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'A user without **Manage** under Document Management creating, editing or deleting a master document, generating a transmittal, or uploading a template. If any of these succeeds, that is a serious defect — report it.',
            "A user who is not on the project team reading that project's documents.",
          ],
        },
      ],
    },
    {
      id: 'UAT-DOC-18',
      title: 'Company Documents registry: upload, new version, delete',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'company-wide SOPs, policies and templates are stored in one place with version history. This is the **Documents** item in the sidebar — it is separate from project document control.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'an admin (**Manage Users**). Everyone else can read and download but not upload.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'two versions of a policy document (any two files).',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Sidebar **SETUP → Documents**',
              'Page **Company Documents**, subtitle *"SOPs, policies, templates, and company-wide resources"*, with tabs **All**, **SOPs**, **Policies**, **Templates**, **Standards**, **Manuals**, **Other**',
            ],
            [
              '2',
              'Click **Upload Document**',
              'An upload form with a title, description, category and tags',
            ],
            [
              '3',
              'Upload the first file as an SOP, with a title and description',
              'The row appears under the **SOPs** tab, chipped `v1`',
            ],
            ['4', "Click the row's download action", 'The file downloads correctly'],
            [
              '5',
              "Open the row's **⋮** menu and choose **Upload New Version**",
              'An upload dialog for a replacement file',
            ],
            ['6', 'Upload the second file with a version note', "The row's chip changes to `v2`"],
            [
              '7',
              'Click the version chip (tooltip **View version history**)',
              'Dialog **Version History: {title}** listing both versions with their uploader, date and notes',
            ],
            [
              '8',
              'Download v1 from the history',
              'The original file downloads — old versions are still retrievable',
            ],
            [
              '9',
              'Choose **Edit Details** from the ⋮ menu, change the description, save',
              'The change sticks after a reload',
            ],
            [
              '10',
              'Search for the document by a word in its description',
              'It is found; searching by title and by tag also works',
            ],
            ['11', 'Choose **Delete**, confirm on the **Delete Document** dialog', 'The row goes'],
            [
              '12',
              '**As a non-admin user**, open the same page',
              'Documents are readable and downloadable, but **Upload Document** and the ⋮ menu are not offered',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'This page must not show any project master documents, and the project Documents page must not show these company documents. They are two separate registers.',
          ],
        },
      ],
    },
  ],
  gaps: [
    {
      text: '**Auto-numbering can only be set up on an empty project.** The **Set Up Auto-Numbering** offer only appears while a project has zero documents. Once the first document exists — including one created by an import — there is no way in, and the project is stuck on manual numbering forever. Affects UAT-DOC-01.',
      group: 'Document control',
    },
    {
      text: '**Transmittals cannot be marked Sent or Acknowledged.** Both statuses exist but neither has a button, so every transmittal stays at **GENERATED**. Affects UAT-DOC-14.',
      group: 'Document control',
    },
    {
      text: '**A Comment Resolution Sheet cannot be marked complete.** There is no control to move a CRS off **Pending**, and no automatic comment extraction — comments from the sheet must be typed in by hand. Affects UAT-DOC-11 step 10.',
      group: 'Document control',
    },
    {
      text: "**A transmittal's ZIP contains one file per document, not the native and PDF pair.** If a submission has both a DWG and a PDF, only one goes into the package. Affects UAT-DOC-12.",
      group: 'Document control',
    },
    {
      text: '**The client name on every transmittal is the literal text "Client Name".** It is not taken from the project\'s customer. It appears on the cover sheet PDF and in the transmittal detail dialog. Affects UAT-DOC-12.',
      group: 'Document control',
    },
    {
      text: '**The transmittal document filter has a dead option.** On the document-selection step, choosing **Client Review** always returns zero documents. Affects UAT-DOC-12.',
      group: 'Document control',
    },
    {
      text: "**The grouped view's Submit shortcut goes nowhere useful.** Clicking the submit icon on a grouped row lands you on the document's Overview tab instead of the submission screen. Use the Revisions tab instead. Affects UAT-DOC-05.",
      group: 'Document control',
    },
    {
      text: '**Status text is written three different ways.** The master document list shows `IN PROGRESS`, the document detail header shows `IN_PROGRESS` with an underscore, and the edit dropdown shows `In Progress`. They are the same status. Affects UAT-DOC-05 and UAT-DOC-08.',
      group: 'Document control',
    },
    {
      text: '**The transmittals empty state names a button that does not exist.** It tells you to click *"Create Transmittal"*; the button is **Generate Transmittal**. Affects UAT-DOC-13.',
      group: 'Document control',
    },
    {
      text: "**The CRS upload dialog's Notes box is not saved.** Anything typed there is discarded. Affects UAT-DOC-11.",
      group: 'Document control',
    },
    {
      text: '**The client review status on a submission is display-only.** A submission always shows **Pending**; there is no control to record that the client approved it or approved it with comments. Affects UAT-DOC-06.',
      group: 'Document control',
    },
    {
      text: '**There is no way to push BOM items into a purchase request.** BOMs carry only their proposal or enquiry link. Procurement is fed from the project charter\'s procurement items instead. Do not look for a "create PR from BOM" button — there isn\'t one.',
      group: 'Estimation',
    },
  ],
};

export default documentsGuide;
