// GENERATED by scripts/generate-workflow-guide.mjs — do not edit by hand.
// Source: docs/workflows/user-testing/uat-entities-ssot-thermal.md
import type { WorkflowGuideModule } from './types';

export const entitiesGuide: WorkflowGuideModule = {
  id: 'entities',
  label: 'Entities & Process Data',
  intro: [
    {
      section: 'What this module does',
      blocks: [
        {
          k: 'p',
          text: "**Entity Management** is the company's master list of everyone we do business with — vendors, customers and partners. Each entity carries its contact people, billing and shipping addresses, PAN and GSTIN, bank accounts, credit terms and an opening balance carried forward from the previous year. Every purchase order, bill, invoice and payment in the app points back to one of these records, so a mistake here spreads everywhere.",
        },
        {
          k: 'p',
          text: '**Process Data (SSOT)** is the per-project engineering master used to build P&IDs and datasheets. For a chosen project it holds the **Streams** (the fluids and their conditions), the **Equipment** they flow through, the **Lines** (pipes, with automatic sizing), the **Instruments** and **Valves** on those lines, and a **Pipe Table** of standard sizes used when sizing a line. Records are linked to each other by tag text — exactly the way the source engineering spreadsheets are keyed.',
        },
        {
          k: 'p',
          text: '**Thermal Calculators** is a suite of around thirty standalone design calculators for MED / MED-TVC / MSF desalination plants, plus a full **MED Plant Designer** wizard, a **Flash Chamber Calculator**, and a read-only **Reference Projects** library of as-built plant data. Most calculators compute as you type; most let you save a named set of inputs and load it back later.',
        },
      ],
    },
    {
      section: 'Before you start',
      blocks: [
        {
          k: 'h',
          text: 'Permissions you need',
        },
        {
          k: 'table',
          steps: false,
          head: ['What you want to test', 'Permission needed'],
          rows: [
            ['Open Entity Management, see the list and View Details', '**View Entities**'],
            [
              'New Entity, Edit Entity, Archive, Unarchive',
              '**Create Entities** (there is no separate "edit" permission)',
            ],
            ['**View Ledger** on an entity row', '**View Accounting**'],
            ['Open Process Data (SSOT) and read all six tabs', '**View Thermal Desalination**'],
            [
              'Add / edit / delete anything in Process Data',
              '**Manage Process Data (SSOT)** *and* you must be assigned to the project you are editing',
            ],
            [
              'Open Thermal Calculators, run and save calculations',
              'None — open to every signed-in user',
            ],
          ],
        },
        {
          k: 'p',
          text: 'Permission changes take a few minutes to reach someone who is already signed in. Have them sign out and back in before reporting a permission problem.',
        },
        {
          k: 'h',
          text: 'Test data you need first',
        },
        {
          k: 'ul',
          items: [
            '**A project you are assigned to.** Everything in Process Data hangs off a project chosen from the **Select Project** dropdown, and you cannot save anything on a project you are not assigned to. Sort this out before starting the SSOT tests.',
            '**A note pad, physical or otherwise.** The round-trip tests (UAT-ENT-03, and one per Process Data record type) ask you to write down every value you typed and compare it after saving. Do not trust memory — the whole point of the test is spotting a single field that silently changed.',
            '**A vendor with at least one purchase order against it** for UAT-ENT-11, and **a vendor or customer with a few posted transactions** for UAT-ENT-10.',
            '**A calculator or two you know the answer to.** For the thermal sweep, being able to say "that number is about right for a plant this size" is worth far more than confirming a number appeared.',
          ],
        },
        {
          k: 'h',
          text: 'A second user — read this before you start',
        },
        {
          k: 'p',
          text: 'Three tests need one.',
        },
        {
          k: 'table',
          steps: false,
          head: ['Account', 'What it needs', 'Used by'],
          rows: [
            ['**A limited user**', '**View Entities** but **not** Create Entities', 'UAT-ENT-12'],
            [
              '**A limited user**',
              '**View Thermal Desalination** but **not** Manage Process Data (SSOT); or a user not assigned to your test project',
              'UAT-SSOT-09',
            ],
            [
              '**A colleague**',
              "Any account that can open the same project's Process Data",
              'UAT-SSOT-08',
            ],
            ['**A colleague**', 'Any signed-in account', 'UAT-THRM-05'],
          ],
        },
        {
          k: 'h',
          text: 'Sidebar',
        },
        {
          k: 'ul',
          items: [
            'Entities: **SETUP → Entity Management**',
            'Process Data: **ENGINEERING DATA → Process Data (SSOT)**',
            'Thermal: **SALES & ESTIMATION → Thermal Calculators**',
          ],
        },
        {
          k: 'p',
          text: '**Read the [Known issues in this module](#known-issues-in-this-module) section at the bottom before you start.** Eight things are already known to be broken or missing; please do not spend time filing them again.',
        },
        {
          k: 'h',
          text: 'A note for engineering testers',
        },
        {
          k: 'p',
          text: 'On every thermal and process-data test, "a number appeared" is not a pass. Check three things each time:',
        },
        {
          k: 'ol',
          items: [
            '**The unit is shown, and it is the unit you expected.** mbar vs bar and kg/s vs T/h are the two that bite.',
            '**The magnitude is physically plausible** for the plant you described. A 4-metre shell for a 100 m³/day unit is wrong even if it computes.',
            '**The result moves the right way when you change an input.** Double the flow and the pipe should get bigger, not smaller.',
          ],
        },
        {
          k: 'p',
          text: 'Anything that fails one of those three is worth a Feedback item even if nothing on screen looks like an error.',
        },
      ],
    },
  ],
  workflows: [
    {
      id: 'UAT-ENT-01',
      title: 'Browse the entity master and its filters',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the list shows every counterparty correctly and that search, filters, sorting and paging all behave.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone with **View Entities**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'nothing. Ideally there are already a few vendors and customers in the system.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Sidebar → **SETUP → Entity Management**',
              'A page titled **Entity Management**, subtitle "Manage vendors, customers, and business partners"',
            ],
            [
              '2',
              'Read the five cards across the top',
              '**Total Entities**, **Active**, **Archived**, **Vendors**, **Customers**',
            ],
            ['3', 'Add the Active and Archived numbers together', 'They equal **Total Entities**'],
            [
              '4',
              'Read the table columns',
              'Entity Name, Roles, Contact Person, State, Opening Balance, Status, Actions',
            ],
            [
              '5',
              'Look at a row for a vendor with no billing state recorded',
              'The **State** cell reads **Not set** in red — that is deliberate, it flags an entity that will cause GST problems later',
            ],
            [
              '6',
              'Look at a row with an opening balance',
              'An amount in rupees, followed by a small **DR** or **CR**; **CR** is shown in red, **DR** in green. A row with no opening balance shows a dash',
            ],
            [
              '7',
              'Type part of an entity name into **Search entities...**',
              'The table narrows as you type',
            ],
            [
              '8',
              'Clear search. Set **Status** to **Archived**',
              'Only archived entities remain, each with an orange **Archived** chip',
            ],
            [
              '9',
              'Set **Status** back to **All Status**. Set **Role** to **Vendor**',
              'Only entities carrying a **VENDOR** chip remain',
            ],
            [
              '10',
              'With Role still on **Vendor**, a **Vendor Category** dropdown appears — pick **Bought Out Items**',
              'A further **Sub-Category** dropdown appears next to it',
            ],
            [
              '11',
              'Set Role to **Supplier**',
              '⚠ known issue — the list comes back empty no matter what. The create form cannot produce a Supplier, so this filter never matches. Do not file this',
            ],
            [
              '12',
              'Set Role back to **All Roles**. Click the **Entity Name** column heading',
              'The list re-sorts alphabetically; click again and it reverses',
            ],
            ['13', 'Do the same on **Contact Person** and **Status**', 'Both sort and reverse'],
            [
              '14',
              'Change the rows-per-page control at the bottom to 25, then 50',
              'Paging works and the total count stays the same',
            ],
            [
              '15',
              'Search for a string that matches nothing',
              'An empty-state message rather than a blank table',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Role chips are colour-coded: **VENDOR** blue, **CUSTOMER** green, anything else grey.',
            'Opening balance amounts are formatted in rupees with two decimals, not raw numbers.',
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-02',
      title: 'Create a vendor with every field filled in',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'create one complete vendor record, using every section of the form, and confirm it lands in the list correctly.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Create Entities**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'nothing. **Write down every value you type** — UAT-ENT-03 checks them all come back.',
        },
        {
          k: 'note',
          text: 'Pick a name you will recognise later, e.g. `UAT Test Vendor 01`.',
          warn: false,
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Click **New Entity**',
              'A dialog titled **Create New Entity** with sections: Basic Information, Contact Persons, Address & Tax Information, Shipping Address (Optional), Bank Details (Optional), Credit Terms & Opening Balance (Optional)',
            ],
            [
              '2',
              '**Entity Name** → `UAT Test Vendor 01`. **Legal Name** → `UAT Test Vendor Private Limited`',
              'Both accept text; Legal Name says it can be left blank if the same',
            ],
            [
              '3',
              'Open **Entity Roles** and tick **VENDOR**',
              'A **VENDOR** chip appears in the field, and a new **Vendor Categorization** section appears further down the form',
            ],
            [
              '4',
              'Under **Contact Persons** click **Add Contact**. Fill Name, Designation, Email, Phone, Mobile, Notes. Click **Add Contact**',
              'The contact appears in a card with a **Primary** chip — the first contact is always the primary',
            ],
            [
              '5',
              'In **Address & Tax Information** fill Address Line 1, Address Line 2, City, **State** (from the dropdown), Postal Code, Country',
              'State is a fixed list of Indian states, not free text',
            ],
            [
              '6',
              'Enter a valid **PAN**, e.g. `AAACU9603R`',
              'The field accepts it and shows no error',
            ],
            [
              '7',
              'Enter a valid **GSTIN** for the same PAN, e.g. `29AAACU9603R1ZM`',
              'Accepted, no error',
            ],
            [
              '8',
              'In **Shipping Address (Optional)** tick **Same as billing address**',
              'The shipping fields disappear or fill themselves from billing',
            ],
            [
              '9',
              'Untick it and fill a **different** shipping address completely',
              'All six shipping fields accept values independently',
            ],
            [
              '10',
              'Under **Bank Details (Optional)** click **Add Bank Account**. Fill Bank Name, Account Name, Account Number, IFSC Code, SWIFT Code, IBAN, Branch Name, Branch Address. Click **Add Bank Account**',
              'The account appears as a card and the header now reads **Bank Details (1)**',
            ],
            [
              '11',
              'Fill **Credit Days** = `45` and **Credit Limit (INR)** = `500000`',
              'Helper text explains credit days are counted from the invoice date',
            ],
            [
              '12',
              'Fill **Opening Balance (INR)** = `50000` and set **Balance Type** to **Credit (CR)**',
              'The helper line reads "DR = They owe us (advance given) \\',
            ],
            [
              '13',
              'In **Vendor Categorization** pick two **Vendor Categories**, one of them **Bought Out Items**',
              'A **Bought Out Sub-Category** field appears',
            ],
            [
              '14',
              'Fill **Bought Out Sub-Category** = `Valves` and **Services Offered** = `Ball valves, Butterfly valves`',
              'Both accept text',
            ],
            [
              '15',
              'Click **Create Entity**',
              'The button shows **Creating...**, then the dialog closes and the new row appears at the top of the list',
            ],
            [
              '16',
              'Read the new row',
              "Name, a **VENDOR** chip, your primary contact's name, the billing state, `₹50,000.00 CR` in red, and a green **Active** chip",
            ],
            ['17', 'Check the **Total Entities** and **Vendors** cards', 'Both went up by one'],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'The **Vendor Categorization** section is present *only* because you picked VENDOR. Untick VENDOR and it should vanish.',
            'The opening balance colour matches the type you chose — **CR** red, **DR** green.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Creating an entity with no name — **Create Entity** must refuse it.',
            'Creating an entity with **no contact person at all** — at least one contact is required.',
            'Saving with a badly-formed PAN or GSTIN — the field must show an error and block the save.',
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-03',
      title: 'Entity round-trip — nothing lost between save and reopen',
      knownIssue: false,
      blocks: [
        {
          k: 'note',
          text: '**This is the most valuable test in the entity section.** The form has roughly forty fields across seven sections, most of them optional. A field that is written on create but not read back on edit is the commonest defect in this app, and it is invisible until somebody notices their bank details vanished.',
          warn: false,
        },
        {
          k: 'meta',
          label: 'Goal',
          text: 'reopen the vendor you just created, confirm every single value survived, save again unchanged, and confirm it survived a second time.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Create Entities**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires **UAT Test Vendor 01** from UAT-ENT-02, with your written list of values in front of you.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Find the row, open the actions menu at the end of it, choose **Edit Entity**',
              'A dialog titled **Edit Entity**',
            ],
            [
              '2',
              '**Basic Information** — check Entity Name, Legal Name, and that the **VENDOR** chip is in Entity Roles',
              'All three exactly as typed',
            ],
            [
              '3',
              "**Contact Persons** — check the contact's Name, Designation, Email, Phone, Mobile **and Notes**",
              'All six values present; the **Primary** chip is still on that contact',
            ],
            [
              '4',
              '**Address & Tax Information** — check Address Line 1, Line 2, City, State, Postal Code, Country',
              'All six exactly as typed; **State** shows the state you picked, not blank',
            ],
            ['5', 'Check **PAN** and **GSTIN**', 'Both present and unchanged'],
            [
              '6',
              '**Shipping Address** — check all six fields',
              'The *different* shipping address you entered, not a copy of billing',
            ],
            [
              '7',
              '**Bank Details** — check the header count, then all eight fields on the account',
              'Header reads **Bank Details (1)**; Bank Name, Account Name, Account Number, IFSC, SWIFT, IBAN, Branch Name, Branch Address all present',
            ],
            [
              '8',
              '**Credit Terms & Opening Balance** — check Credit Days, Credit Limit, Opening Balance and Balance Type',
              '`45`, `500000`, `50000`, and **Credit (CR)** still selected',
            ],
            [
              '9',
              '**Vendor Categorization** — check both Vendor Categories, Services Offered and Bought Out Sub-Category',
              'All present; the sub-category field is still shown because Bought Out Items is still selected',
            ],
            [
              '10',
              '**Without changing a single thing**, click **Update Entity**',
              'Saves cleanly and the dialog closes',
            ],
            [
              '11',
              'Reopen **Edit Entity**',
              '**Every value is still there, unchanged.** Go through steps 2–9 a second time against your notes',
            ],
            [
              '12',
              'Change exactly one value — say Credit Days to `60` — and click **Update Entity**',
              'Only that one value changed; everything else is untouched when you reopen',
            ],
            [
              '13',
              'Reopen, add a **second** bank account with all eight fields, save, reopen',
              '**Bank Details (2)** and both accounts complete',
            ],
            [
              '14',
              'Reopen, clear an optional field completely — say **Branch Address** on the second account — and save',
              'Report what happens: does the field come back blank, or does the old value return?',
            ],
            [
              '15',
              'Reload the whole page, then open **Edit Entity** once more',
              'Still everything, after a full page refresh',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'The Entity Roles field is a **multi-select** — adding CUSTOMER alongside VENDOR and saving must not drop VENDOR.',
            'Numbers come back as numbers, not as text with stray spaces.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Editing an entity that has been archived — the **Edit Entity** action must not be offered at all until it is restored.',
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-04',
      title: 'Contacts — add, edit, delete, and the primary-contact rule',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the contact list inside the entity form behaves, including the rule that exactly one contact is primary.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Create Entities**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires **UAT Test Vendor 01**, currently with one contact.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Open **Edit Entity** on the vendor and find **Contact Persons**',
              'Header reads **Contact Persons (1)**; the one contact carries a **Primary** chip',
            ],
            [
              '2',
              'Click **Add Contact**, fill Name only, click **Add Contact**',
              'A second card appears with **no** Primary chip; header now **(2)**',
            ],
            [
              '3',
              'Try to add a contact with the Name box empty',
              'The **Add Contact** confirm button stays disabled — name is required',
            ],
            [
              '4',
              'Click the star icon on the second contact',
              'The **Primary** chip moves to it; the first contact loses it. Only ever one primary',
            ],
            [
              '5',
              'Hover the star on the contact that *is* primary',
              'It is disabled — you cannot un-primary without promoting someone else',
            ],
            [
              '6',
              'Click the pencil on the first contact, change the Designation, click **Save**',
              'The card updates in place; nothing else on it changed',
            ],
            [
              '7',
              'Click the pencil, then **Cancel**',
              'The edit is abandoned and the original values are still shown',
            ],
            ['8', 'Add a third contact with every field filled', 'Header reads **(3)**'],
            [
              '9',
              'Delete the contact that is currently **Primary** (trash icon)',
              'It disappears, and one of the remaining contacts is automatically promoted to **Primary**',
            ],
            [
              '10',
              'Click **Update Entity**, then reopen **Edit Entity**',
              'The exact set of contacts, with the same primary, and every field on each contact intact',
            ],
            [
              '11',
              'Delete contacts down to one, save, reopen',
              'One contact, and it is the primary',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            "The entity row in the list shows the **primary** contact's name in the **Contact Person** column. Change which contact is primary, save, and the list column should follow.",
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-05',
      title: 'Bank accounts — add several, edit, delete',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm multiple bank accounts can be held against one entity and survive a save.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Create Entities**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires **UAT Test Vendor 01**.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Open **Edit Entity** and find **Bank Details**',
              'Header shows the count in brackets',
            ],
            [
              '2',
              'Click **Add Bank Account** and fill only Bank Name',
              'The confirm button stays disabled — Bank Name, Account Name and Account Number are all required',
            ],
            [
              '3',
              'Fill Account Name and Account Number too, then click **Add Bank Account**',
              'The card appears; the count goes up',
            ],
            [
              '4',
              'Add a third account, this time an **international** one — SWIFT Code and IBAN filled, IFSC blank',
              'Accepted; IFSC is optional',
            ],
            [
              '5',
              'Click the pencil on one account, change the Branch Name, click **Save**',
              'Updated in place',
            ],
            ['6', 'Click the pencil, then **Cancel**', 'Original values still shown'],
            [
              '7',
              'Delete the middle account (trash icon)',
              'It goes; the other two are untouched and the count drops',
            ],
            [
              '8',
              'Click **Update Entity**, reopen **Edit Entity**',
              'Exactly the accounts you left, each with all eight fields intact',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Bank accounts have **no primary flag** — unlike contacts, none is marked. If you see a Primary chip on a bank account, that is new and worth reporting.',
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-06',
      title: 'Create a customer, and an entity that is both vendor and customer',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the customer path works and that a dual-role entity behaves in the list and in both modules.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Create Entities**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'nothing.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              '**New Entity** → Name `UAT Test Customer 01`, Entity Roles → **CUSTOMER** only',
              'A **CUSTOMER** chip; the **Vendor Categorization** section is **not** shown',
            ],
            [
              '2',
              'Add one contact, a billing state, a GSTIN, and an opening balance of `25000` **Debit (DR)**',
              'All accepted',
            ],
            [
              '3',
              'Click **Create Entity**',
              'The row appears with a green **CUSTOMER** chip and `₹25,000.00 DR` in green',
            ],
            [
              '4',
              'Check the **Customers** card at the top',
              'It went up by one; the **Vendors** card did not',
            ],
            [
              '5',
              '**New Entity** → Name `UAT Test Both 01`, tick **VENDOR** *and* **CUSTOMER**',
              'Two chips in the field; the Vendor Categorization section appears',
            ],
            [
              '6',
              'Fill a contact and create it',
              'The row shows both a **VENDOR** and a **CUSTOMER** chip',
            ],
            ['7', 'Filter **Role** → **Vendor**', '`UAT Test Both 01` is listed'],
            ['8', 'Filter **Role** → **Customer**', '`UAT Test Both 01` is listed here too'],
            ['9', 'Both the **Vendors** and **Customers** cards', 'Both counted this one entity'],
            [
              '10',
              'Go to a place that picks a vendor (raising a purchase order) and search for `UAT Test Both 01`',
              'It is offered',
            ],
            [
              '11',
              'Go to a place that picks a customer (raising a customer invoice) and search for the same name',
              'It is offered there too',
            ],
            [
              '12',
              'In the same customer picker, search for `UAT Test Vendor 01`',
              'It is **not** offered — a vendor-only entity must not appear as a customer',
            ],
            [
              '13',
              'Add **PARTNER** to `UAT Test Both 01` and save',
              'Three chips; the Role filter **Partner** now finds it',
            ],
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-07',
      title: 'Duplicate and format guards on create',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the app refuses to create a second copy of an entity you already have, and refuses malformed tax IDs.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Create Entities**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires **UAT Test Vendor 01** with its PAN, GSTIN and contact email.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              '**New Entity** → PAN box → type `ABCD`',
              'An error under the field immediately; **Create Entity** is blocked',
            ],
            [
              '2',
              'Type a well-formed but wrong-checksum PAN, e.g. `AAAAA1111A`',
              'Record what happens — accepted or rejected — in the Notes column',
            ],
            ['3', 'GSTIN box → type `29AAACU`', 'An error under the field; save blocked'],
            [
              '4',
              'Now fill a fresh name, one contact, and the **same PAN** as UAT Test Vendor 01. Click **Create Entity**',
              'The create is refused with a message naming the duplicate PAN',
            ],
            [
              '5',
              'Change the PAN, but use the **same GSTIN** as UAT Test Vendor 01',
              'Refused, naming the duplicate GSTIN',
            ],
            [
              '6',
              "Change the GSTIN, but give the contact the **same email** as UAT Test Vendor 01's contact",
              'Refused, naming the duplicate email',
            ],
            [
              '7',
              'Clear PAN, GSTIN and email. Set the name to exactly `UAT Test Vendor 01` and click **Create Entity**',
              '⚠ Refused — but only **after** you click, not while typing. The live check does not look at the name. Do not file this',
            ],
            [
              '8',
              'Set the name to `uat test vendor 01` (all lower case) and click **Create Entity**',
              'Still refused — name matching ignores capitalisation',
            ],
            [
              '9',
              'Set the name to `  UAT Test Vendor 01  ` with leading and trailing spaces',
              'Still refused — spaces are trimmed before comparing',
            ],
            ['10', 'Give it a genuinely new name and click **Create Entity**', 'Created'],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Ending up with two entities that share a name, a PAN or a GSTIN. If you manage it, that is a serious finding — record exactly what you typed.',
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-08',
      title: 'View Details — everything you saved is shown back',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: "confirm the read-only view of an entity shows every section, so a colleague can check a vendor's details without opening the edit form.",
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone with **View Entities**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires **UAT Test Vendor 01**, fully filled in.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              "Open the row's actions menu, choose **View Details**",
              'A dialog headed with the entity name, a **Code:** line beneath it, and a green **Active** chip',
            ],
            [
              '2',
              'Read the code',
              'It looks like `ENT-001` — a three-digit sequence, not a random string',
            ],
            [
              '3',
              'Scroll through the dialog',
              'Sections: Basic Information, Contacts, Billing Address, Tax Information, Shipping Address, Bank Details, Credit Terms, Financial Information, Vendor Categorization',
            ],
            [
              '4',
              'Check **Contacts** against your notes',
              "The right count in the heading, the primary marked, and every contact's details shown",
            ],
            [
              '5',
              'Check **Bank Details**',
              "The right count in the heading, and each account's full details",
            ],
            ['6', 'Check **Tax Information**', 'Your PAN and GSTIN'],
            [
              '7',
              'Check **Financial Information**',
              'The opening balance with the **CR** marker, matching the list row',
            ],
            [
              '8',
              'Check **Vendor Categorization**',
              'Both categories, the services text and the bought-out sub-category',
            ],
            [
              '9',
              'Click the pencil icon in the dialog header',
              'The **Edit Entity** dialog opens on the same entity',
            ],
            [
              '10',
              'Close it, reopen **View Details**, click the archive icon in the header',
              'The **Archive Entity** dialog opens — do not confirm it yet, cancel out',
            ],
            ['11', 'Click **Close**', 'Back to the list, nothing changed'],
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-09',
      title: 'Archive an entity, then restore it',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm an entity can be taken out of circulation without deleting it, and brought back.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Create Entities**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires `UAT Test Customer 01` from UAT-ENT-06. Use the customer, not the vendor — you need the vendor active for later tests.',
        },
        {
          k: 'note',
          text: 'Archiving is reversible, but an archived entity cannot be edited and drops out of the pickers other modules use. Do not archive a real vendor to test this.',
          warn: false,
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              "Open the row's actions menu on `UAT Test Customer 01`",
              '**Archive Entity** is offered; **Unarchive Entity** is not',
            ],
            [
              '2',
              'Choose **Archive Entity**',
              'A dialog titled **Archive Entity** naming the entity, explaining archived entities can be unarchived later',
            ],
            [
              '3',
              'Try to click **Archive Entity** with the reason box empty',
              'The button is disabled — a reason is required',
            ],
            [
              '4',
              'Type a reason, e.g. `UAT test — archiving to check the flow`, then click **Archive Entity**',
              "The dialog closes; the row's status chip turns orange **Archived**",
            ],
            [
              '5',
              'Check the **Active** and **Archived** cards',
              'Active dropped by one, Archived went up by one',
            ],
            ['6', 'Set **Status** to **Active**', 'The archived entity is gone from the list'],
            [
              '7',
              "Set **Status** to **Archived**, open the row's actions menu",
              '**Edit Entity** and **Archive Entity** are **not** offered; **Unarchive Entity** is',
            ],
            [
              '8',
              'Choose **View Details**',
              'The dialog opens with an orange warning banner about the entity being archived, and no pencil or archive icon in the header',
            ],
            [
              '9',
              'Go to a place that picks a customer (raising a customer invoice) and search for the name',
              'It is not offered',
            ],
            [
              '10',
              'Back on the list, choose **Unarchive Entity**',
              'A dialog titled **Unarchive Entity** showing your **Archive Reason**, who archived it and when',
            ],
            ['11', 'Click **Restore Entity**', 'The status chip turns green **Active** again'],
            [
              '12',
              'Open **Edit Entity**',
              'Editing works again, and **every field is exactly as it was before archiving**',
            ],
            ['13', 'Search for it again in the customer picker', 'It is offered once more'],
            [
              '14',
              'Archive an entity that has purchase orders or invoices against it',
              'Record whether the dialog shows an extra warning about existing references before you confirm',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Editing an entity while it is archived.',
            'Archiving an already-archived entity, or restoring one that is already active — the menu must only offer the one that applies.',
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-10',
      title: 'Entity ledger — opening balance, transactions, running balance, ageing',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the ledger reached from an entity row shows the full money history for that counterparty and that the balances add up.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **View Entities** *and* **View Accounting**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'pick an entity that already has an opening balance **and** at least three posted transactions — ideally a customer with an invoice and a part payment.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              "On that entity's row, open the actions menu and choose **View Ledger**",
              'The **Entity Ledger** page opens with the entity already selected in the **Select Entity** box',
            ],
            [
              '2',
              'Read the card at the top',
              'The entity name, its role chips, and an **Opening:** chip showing the opening balance with **DR** or **CR**',
            ],
            [
              '3',
              'Compare that Opening chip with the Opening Balance you saw on the entity list row',
              'Same number, same DR/CR marker',
            ],
            [
              '4',
              'Read the summary cards',
              'For a customer: **Total Invoiced** and **Total Received**. For a vendor: **Total Billed** and **Total Paid**',
            ],
            [
              '5',
              'Read the transactions table columns',
              'Date, Type, Transaction #, Description, Debit, Credit, Balance, Status',
            ],
            [
              '6',
              'Look at the very first row',
              'An **Opening Balance (from prior transactions)** row before any real transaction',
            ],
            [
              '7',
              'Work down the **Balance** column with a calculator',
              "Each row's balance = the row above, plus that row's Debit, minus its Credit. It must run continuously, with no jumps",
            ],
            [
              '8',
              "Check the last row's Balance against the summary cards",
              'Consistent — no unexplained difference',
            ],
            [
              '9',
              'Set **From Date** and **To Date** to a window that excludes the oldest transaction',
              'The table narrows; the opening figure absorbs everything before the window rather than the balance restarting from zero',
            ],
            [
              '10',
              'Clear the dates. Set **Transaction Type** to a single type',
              'Only that type of row remains',
            ],
            [
              '11',
              'Clear the type filter. Scroll to the ageing section',
              '**Receivables Aging Analysis** with buckets **Current (0-30 days)**, **31-60 days** and older, colour-graded',
            ],
            [
              '12',
              'Add up the ageing buckets',
              'They equal the outstanding amount, not the total invoiced',
            ],
            [
              '13',
              'Now go and post a new transaction against this entity in Accounting, then come back and reload the ledger',
              'The new row appears, and the running balance and the summary cards have both moved by the right amount',
            ],
            [
              '14',
              'Click the **Export CSV** icon at the top right',
              'A file downloads; open it and confirm the same rows and the same numbers',
            ],
            ['15', 'Click the **Export Excel** icon', 'A file downloads and opens cleanly'],
            [
              '16',
              'Use the **Select Entity** box to switch to a different entity',
              'The whole page reloads for the new entity — card, summary, table and ageing all change together',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Every amount is in rupees with two decimals. If this entity has transactions in a foreign currency, confirm the ledger totals are still consistent and record what currency the totals are stated in.',
            'A transaction that has been voided or deleted must **not** appear in the ledger or in the totals.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Reaching **View Ledger** at all without **View Accounting** — the menu item must simply not be there.',
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-11',
      title: 'Automatic behaviour — entity codes and the vendor-rename ripple',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the app numbers entities itself, and that renaming a vendor updates the name shown on documents that already reference it.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Create Entities** who can also open Procurement.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires a vendor that has **at least one purchase order** raised against it. Note the PO number.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Create three entities one after another and open **View Details** on each',
              'The **Code:** values run in sequence — `ENT-004`, `ENT-005`, `ENT-006` — with no gaps and no repeats',
            ],
            [
              '2',
              'Have a colleague create one at the same moment as you, if you can arrange it',
              'Both get codes, and they are different',
            ],
            [
              '3',
              'Open the purchase order you noted and write down the vendor name printed on it',
              'The current vendor name',
            ],
            [
              '4',
              'Go to Entity Management, open **Edit Entity** on that vendor and change its **Entity Name**',
              'Saves cleanly',
            ],
            [
              '5',
              'Wait about ten seconds, then reload the purchase order page',
              'The vendor name on the PO has updated on its own to the new name',
            ],
            [
              '6',
              'Check a goods receipt, a packing list and a vendor bill against the same vendor, if any exist',
              'All show the new name after a reload',
            ],
            [
              '7',
              'Open the entity ledger for that vendor',
              'The transaction rows show the new name',
            ],
            [
              '8',
              "Now change the vendor's **contact email** and reload the purchase order",
              'The vendor email on the PO updates too',
            ],
            [
              '9',
              "Now change the vendor's **GSTIN** and reload the purchase order",
              '⚠ known issue — the GSTIN on the PO does **not** change. Name and email propagate; GSTIN does not. Do not file this',
            ],
            ['10', 'Change the vendor name back to what it was', 'The documents follow it back'],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'If somebody had deliberately typed a *different* vendor name onto a document by hand, the rename must **not** overwrite it. Only names that still matched the old value are updated.',
            'The rename happens by itself — there is no button to press and no message to confirm it. If nothing has changed after a minute and a reload, that is the finding.',
          ],
        },
      ],
    },
    {
      id: 'UAT-ENT-12',
      title: 'Permission checks on the entity master',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm that a user who may only look at entities cannot change them, and that a user with no entity permission cannot reach the module at all.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you, plus a second sign-in with **View Entities** but **not** Create Entities.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'ask an admin to set up the limited account, and have that person sign out and back in after the change.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'As the **limited user**, go to **SETUP → Entity Management**',
              'The list opens normally',
            ],
            [
              '2',
              'Look at the top right of the page',
              'There is **no New Entity button at all** — not greyed out, absent',
            ],
            [
              '3',
              "Open a row's actions menu",
              '**View Details** is offered; **Edit Entity**, **Archive Entity** and **Unarchive Entity** are not',
            ],
            [
              '4',
              'Open **View Details**',
              'The dialog opens, but the header has no pencil and no archive icon',
            ],
            [
              '5',
              'If this account also lacks **View Accounting**, check the actions menu again',
              '**View Ledger** is not offered either',
            ],
            [
              '6',
              'Now have an admin remove **View Entities** from that account; sign out and back in',
              '',
            ],
            [
              '7',
              'Go to **SETUP → Entity Management** again',
              'Either the sidebar entry is gone, or the page shows **Access Denied** — "You do not have permission to access the Entity Management module"',
            ],
            ['8', "Restore the account's permissions afterwards", ''],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'A user without **Create Entities** managing to save any change to an entity by any route — including editing from inside the View Details dialog.',
            'Reaching the entity list by typing the address directly when the permission is missing.',
          ],
        },
      ],
    },
    {
      id: 'UAT-SSOT-01',
      title: 'Open Process Data and choose a project',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the module opens, the project picker works, and all six tabs load.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone with **View Thermal Desalination**.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'you must be assigned to at least one project.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Sidebar → **ENGINEERING DATA → Process Data (SSOT)**',
              'A page titled **Process Data (SSOT)**, subtitle "Single Source of Truth for process engineering data"',
            ],
            [
              '2',
              'Look at the **Select Project** dropdown',
              'It has already picked a project for you',
            ],
            ['3', 'Open the dropdown', 'Only projects you are allowed to see are listed'],
            [
              '4',
              'Read the tab strip',
              '**Streams**, **Equipment**, **Lines**, **Instruments**, **Valves**, **Pipe Table**',
            ],
            [
              '5',
              'Click through all six tabs on a project that already has data',
              'Each shows a table with an **Add** button above it, and no error banner',
            ],
            [
              '6',
              'Click through all six tabs on an **empty** project',
              'Each shows an empty table rather than an error or a permanent spinner',
            ],
            [
              '7',
              'Switch to a different project in **Select Project**',
              "The tab you are on reloads with that project's data — data does not leak between projects",
            ],
            [
              '8',
              'Reload the page',
              'You land back on the **Streams** tab with the first project selected',
            ],
            [
              '9',
              'Click **Export Excel**',
              '⚠ known issue — a message reading "Excel export coming soon" and no file. Nothing is exported yet. Do not file this',
            ],
          ],
        },
      ],
    },
    {
      id: 'UAT-SSOT-02',
      title: 'Streams — create, derived values, round-trip, delete',
      knownIssue: false,
      blocks: [
        {
          k: 'note',
          text: 'A stream is the canonical record of a fluid. Everything else in Process Data points back at one, so get this one right first.',
          warn: false,
        },
        {
          k: 'meta',
          label: 'Goal',
          text: 'create a stream with every field, check the calculated properties are sensible, reopen it and confirm nothing was lost, then delete it.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage Process Data (SSOT)**, assigned to the test project.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'pick a project you can safely add test data to. **Write down every value you type.**',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            ['1', '**Streams** tab → **Add Stream**', 'A dialog titled **Add New Stream**'],
            [
              '2',
              'Read the table columns behind it',
              'Line Tag, Fluid Type, Flow (kg/s), Flow (kg/hr), Pressure (mbar), Temp (°C), Density (kg/m³), TDS (ppm), Enthalpy (kJ/kg), Actions',
            ],
            [
              '3',
              '**Line Tag** → `SW1`',
              '**Fluid Type** changes by itself to **SEA WATER** — the tag prefix decides the fluid',
            ],
            [
              '4',
              'Change the tag to `D19`, then `S13`, then back to `SW1`',
              'Fluid Type follows: **DISTILLATE WATER**, then **STEAM**, then **SEA WATER**',
            ],
            [
              '5',
              '**Description** → `UAT test seawater feed to condenser`',
              'Accepts multi-line text',
            ],
            [
              '6',
              '**Flow Rate** → `27.8` (unit shown: **kg/s**), **Pressure** → `1013` (**mbar(a)**), **Temperature** → `30` (**°C**)',
              'All three accept the value with the unit shown beside the box',
            ],
            ['7', '**TDS** → `35000` (**ppm**)', 'Required for seawater — the helper text says so'],
            [
              '8',
              'Read the **Calculated Values (auto-updated)** strip at the bottom of the dialog',
              '**Flow Rate** ≈ `100080.0 kg/hr`, **Pressure** ≈ `1.013 bar(a)`, **Density** around `1020–1025 kg/m³`, an **Enthalpy** in kJ/kg',
            ],
            [
              '9',
              'Sanity-check those four',
              '27.8 kg/s × 3600 = 100 080 kg/hr exactly; 1013 mbar = 1.013 bar; seawater at 30 °C and 35 000 ppm is about 1022 kg/m³',
            ],
            [
              '10',
              'Change **Temperature** to `80` and watch the strip',
              'Density falls, enthalpy rises — both move the right way',
            ],
            [
              '11',
              'Set Temperature back to `30`. Click **Create**',
              'The dialog closes and the row appears in the table with the same numbers',
            ],
            [
              '12',
              'Compare the table row against the dialog values',
              'Flow, pressure, temperature, density, TDS and enthalpy all match, each to its stated unit',
            ],
            [
              '13',
              '**Round trip:** click the pencil on the row',
              'A dialog titled **Edit Stream: SW1**; **every** field — tag, description, flow, pressure, temperature, TDS, fluid type — exactly as typed',
            ],
            [
              '14',
              'Without changing anything, click **Update**, then reopen the pencil',
              'Everything still there, unchanged, including the description',
            ],
            [
              '15',
              'Change **Temperature** to `45` and click **Update**',
              "The row's Temp column shows 45, and **Density and Enthalpy have both recalculated** — they must not be stale",
            ],
            [
              '16',
              'Change only the **Description** and click **Update**',
              'The description changes; density, enthalpy and flow-in-kg/hr are **unchanged**',
            ],
            [
              '17',
              'Add a second stream, `NCG1`, and a third, `B4`',
              'Fluid types come out as **NCG** and **BRINE WATER**',
            ],
            [
              '18',
              'On the `D19` distillate stream, look at the **TDS** field',
              'It is disabled and marked not applicable for that fluid',
            ],
            [
              '19',
              'Click the trash icon on one of the test streams',
              'A confirmation reading "Are you sure you want to delete stream ...? This action cannot be undone." with a **Delete** button',
            ],
            ['20', 'Click **Delete**', 'The row disappears immediately'],
            [
              '21',
              'Reload the page and check the Streams tab',
              'The remaining streams are still there with all their values',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'The pressure is in **mbar absolute** on the way in and **bar absolute** in the calculated strip. A value shown in the wrong one of those is a real defect, not a rounding difference.',
            'Flow in kg/hr must always be exactly 3600 × the kg/s value.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Saving a stream with no Line Tag — the dialog must say **Line Tag is required**.',
            'Saving with a Flow Rate or Pressure of zero — the dialog must say the value must be greater than 0.',
            'Saving a seawater or brine stream with the TDS blank.',
          ],
        },
      ],
    },
    {
      id: 'UAT-SSOT-03',
      title: 'Equipment — create, round-trip, delete, and the stream wiring',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'create an equipment item, wire it to streams by tag, and confirm the round trip.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage Process Data (SSOT)**, assigned to the project.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires at least two streams from UAT-SSOT-02, e.g. `SW1` and `D19`.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            ['1', '**Equipment** tab → **Add Equipment**', 'A dialog titled **Add Equipment**'],
            [
              '2',
              'Read the table columns behind it',
              'Equipment Tag, Equipment Name, Operating Pressure (mbar), Operating Temp (°C), Inlet Streams, Outlet Streams, Actions',
            ],
            [
              '3',
              '**Equipment Tag** → `MED-E1`, **Equipment Name** → `MED Effect 1 Evaporator`',
              'Both accept text',
            ],
            [
              '4',
              '**Operating Pressure** → `250` (**mbar(a)**), **Operating Temperature** → `65` (**°C**)',
              'Units shown beside each box',
            ],
            [
              '5',
              '**Inlet Streams** → `SW1` and **Outlet Streams** → `D19`',
              'Helper text says comma-separated stream tags',
            ],
            [
              '6',
              'Click **Create**',
              'The row appears with your tags listed in the Inlet and Outlet columns',
            ],
            [
              '7',
              '**Round trip:** click the pencil',
              '**Edit Equipment** with all six values exactly as typed — including both stream-tag lists',
            ],
            [
              '8',
              'Without changing anything, click **Update**, reopen the pencil',
              'Everything unchanged',
            ],
            [
              '9',
              'Add a second inlet stream tag alongside the first, comma-separated, and **Update**',
              'Both tags appear in the Inlet Streams column and both come back on reopening',
            ],
            [
              '10',
              'Type a stream tag that does not exist, e.g. `ZZ99`, and **Update**',
              'Record what happens. There is no check that the tag is real — this is expected today, note it and move on',
            ],
            [
              '11',
              'Add a second piece of equipment, `LTFV`, with different values',
              'Both rows listed',
            ],
            [
              '12',
              'Delete the second one (trash icon → confirm **Delete**)',
              'Confirmation titled **Delete Equipment**, then the row goes',
            ],
            ['13', 'Reload the page', '`MED-E1` is still there with everything intact'],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: ['Saving with no Equipment Tag.'],
        },
      ],
    },
    {
      id: 'UAT-SSOT-04',
      title: 'Pipe Table — load the standard table, add, edit, delete a size',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'get the standard pipe size lookup in place for this project, so line sizing has something to work against.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage Process Data (SSOT)**, assigned to the project.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'ideally a project whose Pipe Table is still empty. **Run this before UAT-SSOT-05.**',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              '**Pipe Table** tab',
              'The line "Pipe sizing lookup table (ASME B36.10 Schedule 40)" and, on an empty project, a **Load Default Table** button next to **Add Size**',
            ],
            [
              '2',
              'Read the table columns',
              'ID Range Min (mm), ID Range Max (mm), Pipe Size (NB), OD (mm), Thickness Sch40 (mm), ID (mm), Actions',
            ],
            [
              '3',
              'Click **Load Default Table**',
              'A confirmation saying it will add **19 standard pipe sizes** based on ASME B36.10 Schedule 40',
            ],
            ['4', 'Click **Load**', '19 rows appear, in ascending size order'],
            [
              '5',
              'Check a row you know — e.g. 100 NB',
              'OD `114.3` mm, Sch 40 thickness `6.02` mm, and ID = OD − 2 × thickness = `102.26` mm',
            ],
            [
              '6',
              'Check the **ID (mm)** column on three more rows with a calculator',
              'Every one equals OD − 2 × thickness. This column is computed, not typed',
            ],
            [
              '7',
              'Check the **Load Default Table** button',
              'It has disappeared now that the table has rows — it only offers itself on an empty table',
            ],
            [
              '8',
              'Click **Add Size**. Fill ID Range Min, ID Range Max, Pipe Size NB, Outer Diameter, Thickness Sch40',
              'A dialog titled **Add Pipe Size**',
            ],
            ['9', 'Click **Create**', 'The row appears with the ID column filled in for you'],
            [
              '10',
              '**Round trip:** click the pencil on your new row',
              '**Edit Pipe Size** with all five typed values exactly as entered',
            ],
            [
              '11',
              'Change the Thickness and click **Update**',
              'The **ID (mm)** column recalculates on its own',
            ],
            [
              '12',
              'Delete your added row (trash → **Delete**)',
              'Confirmation titled **Delete Pipe Size**, then the row goes; the 19 standard rows are untouched',
            ],
          ],
        },
      ],
    },
    {
      id: 'UAT-SSOT-05',
      title: 'Lines — automatic pipe sizing, round-trip, recalculation, delete',
      knownIssue: false,
      blocks: [
        {
          k: 'note',
          text: 'This is the one place in Process Data where the app does real engineering for you. Check the arithmetic, not just that the boxes fill in.',
          warn: false,
        },
        {
          k: 'meta',
          label: 'Goal',
          text: 'create a line that draws its flow from a stream, confirm the calculated bore and actual velocity are right, and confirm the round trip.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage Process Data (SSOT)**, assigned to the project.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires stream `SW1` from UAT-SSOT-02 and the pipe table from UAT-SSOT-04.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            ['1', '**Lines** tab → **Add Line**', 'A dialog titled **Add Line**'],
            [
              '2',
              'Read the table columns behind it',
              'S.No, Line No., Fluid, Input Tag, Flow (kg/s), Density (kg/m³), Calc. Velocity (m/s), Calc. ID (mm), Selected ID (mm), Actual Velocity (m/s), Actions',
            ],
            [
              '3',
              '**S.No** → `1`, **Line Number** → `200-40-SS-SW-01`, **Input Data Tag** → `SW1`, **Fluid** → `Sea water`',
              'All four accept text',
            ],
            [
              '4',
              "Open the **Streams** tab in another browser tab and read `SW1`'s flow and density",
              'Note them — you are about to copy them across by hand. The line does **not** fetch them for you',
            ],
            [
              '5',
              "**Flow Rate** → the stream's kg/s value, **Density** → the stream's kg/m³ value",
              'Units **kg/s** and **kg/m³** shown beside the boxes',
            ],
            [
              '6',
              'Under **Pipe Sizing**, **Design Velocity** → `2.0` (**m/s**)',
              'The read-only **Calculated ID** box beside it fills in with a value in mm',
            ],
            [
              '7',
              'Sanity-check the Calculated ID',
              'For 27.8 kg/s at 1022 kg/m³ and 2 m/s, the required bore is about **133 mm**. Anything an order of magnitude away is a defect',
            ],
            [
              '8',
              'Halve the Design Velocity to `1.0` and watch the Calculated ID',
              'It grows by about 40 % (√2), not by 2× — slower water needs a bigger, but not double, bore',
            ],
            [
              '9',
              'Set Design Velocity back to `2.0`. Look up the next standard size **above** the Calculated ID in the Pipe Table tab',
              'e.g. 150 NB, ID `154.05` mm',
            ],
            [
              '10',
              'Type that ID into **Selected ID** (**mm**)',
              'The read-only **Actual Velocity** box fills in',
            ],
            [
              '11',
              'Sanity-check the Actual Velocity',
              'It must be **lower** than your design velocity, because you rounded the bore up. Roughly 1.5 m/s here',
            ],
            [
              '12',
              'Type a deliberately small Selected ID, e.g. `50`',
              'Actual Velocity jumps well above the design velocity — the tool does not silently clamp it',
            ],
            [
              '13',
              'Set Selected ID back to the sensible value and click **Create**',
              'The row appears with Calc. ID, Selected ID and Actual Velocity all populated',
            ],
            [
              '14',
              '**Round trip:** click the pencil',
              '**Edit Line** with S.No, Line Number, Input Data Tag, Fluid, Flow Rate, Density, Design Velocity and Selected ID **all exactly as typed**',
            ],
            [
              '15',
              'Without changing anything, click **Update**, reopen',
              'Everything unchanged, including the calculated columns',
            ],
            [
              '16',
              'Change **Flow Rate** only, and **Update**',
              'Calc. ID **and** Actual Velocity both move; they must not be left stale',
            ],
            [
              '17',
              'Change **Selected ID** only, and **Update**',
              'Actual Velocity moves; Calc. ID does not',
            ],
            [
              '18',
              'Change the **Fluid** text only, and **Update**',
              'None of the calculated columns change',
            ],
            [
              '19',
              'Add a second line drawing from a different stream',
              'Both rows listed, sorted sensibly',
            ],
            [
              '20',
              'Delete the second line (trash → **Delete**)',
              'Confirmation titled **Delete Line**, then the row goes',
            ],
            ['21', 'Reload the page', 'The first line survives with every value'],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Update the **stream** `SW1` to a different flow rate. The line does **not** follow it — you must edit the line too. That is how it works today; confirm it, and note in the Notes column whether that surprised you.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Saving a line with no Line Number — the tab must show **Line number is required**.',
          ],
        },
      ],
    },
    {
      id: 'UAT-SSOT-06',
      title: 'Instruments — create, round-trip, delete',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'create an instrument datasheet row, confirm it links to a line and a valve by tag, and confirm the round trip.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage Process Data (SSOT)**, assigned to the project.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires the line from UAT-SSOT-05. **Write down every value.**',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            ['1', '**Instruments** tab → **Add Instrument**', 'A dialog titled **Add Instrument**'],
            [
              '2',
              'Read the table columns behind it',
              'S.No, Tag No., Type, Line No., Service Location, Fluid, Pressure (mbar), Temp (°C), Flow (kg/hr), Actions',
            ],
            ['3', 'Fill **S.No** `1` and **Tag No.** `PIT-101`', 'Both accept'],
            [
              '4',
              'Open **Instrument Type**',
              'A fixed list — Pressure Indicating Transmitter, Pressure Gauge, Temperature Indicator, Temperature Transmitter, Flow Transmitter, Level Transmitter and so on. Not free text',
            ],
            ['5', 'Pick **Pressure Indicating Transmitter**', 'Selected'],
            [
              '6',
              'Fill **Instrument Valve No.** `IV-101`, **P&ID No.** `PID-001`, **Line No.** `200-40-SS-SW-01`, **Fluid** `Sea water`, **Service Location** `Condenser inlet`',
              'All five accept text',
            ],
            [
              '7',
              'Fill **Pressure** `1013` (**mbar(a)**), **Temperature** `30` (**°C**), **Flow Rate** `100080` (**kg/hr**)',
              'Units shown beside each',
            ],
            ['8', 'Click **Create**', 'The row appears with all nine columns filled'],
            [
              '9',
              '**Round trip:** click the pencil',
              '**Edit Instrument** with **all eleven** typed values exactly as entered — including P&ID No. and Instrument Valve No., which are not shown in the table',
            ],
            ['10', 'Without changing anything, click **Update**, reopen', 'Everything unchanged'],
            [
              '11',
              'Change the **Instrument Type** to **Flow Transmitter** and **Update**',
              'The Type column changes; nothing else does',
            ],
            [
              '12',
              'Add a second instrument with **only** Tag No. filled and everything else blank, then reopen it',
              'The blank fields come back blank — an empty optional field must not acquire a value from anywhere',
            ],
            [
              '13',
              'Delete the second one (trash → **Delete**)',
              'Confirmation titled **Delete Instrument**, then the row goes',
            ],
            ['14', 'Reload the page', '`PIT-101` survives intact'],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: ['Saving with no Tag No. — the tab must show **Tag number is required**.'],
        },
      ],
    },
    {
      id: 'UAT-SSOT-07',
      title: 'Valves — create, round-trip, delete',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'create a valve datasheet row and confirm the round trip, including the two dropdown fields.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'someone with **Manage Process Data (SSOT)**, assigned to the project.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires the line from UAT-SSOT-05. **Write down every value.**',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            ['1', '**Valves** tab → **Add Valve**', 'A dialog titled **Add Valve**'],
            [
              '2',
              'Read the table columns behind it',
              'S.No, Valve Tag, Type, Size, Line No., Service Location, Fluid, Pressure (bar), Temp (°C), ΔP (bar), Actions',
            ],
            ['3', 'Fill **S.No** `1` and **Valve Tag** `BFV-101`', 'Both accept'],
            [
              '4',
              'Open **Valve Type**',
              'A fixed list — Ball Valve, Butterfly, Gate Valve, Globe Valve, Check Valve, Non Return Valve, Motorized Globe Valve, Control Valve, Safety Valve, Relief Valve',
            ],
            ['5', 'Pick **BUTTERFLY**', 'Selected'],
            [
              '6',
              'Fill **Size (NB)** `150`, **P&ID No.** `PID-001`, **Line Number** `200-40-SS-SW-01`',
              'All three accept',
            ],
            [
              '7',
              'Open **End Connection**',
              'A fixed list — Threaded, Flanged, Welded, Socket Weld. Pick **FLANGED**',
            ],
            [
              '8',
              'Fill **Service Location** `Condenser inlet isolation`, **Fluid** `Sea water`',
              'Both accept',
            ],
            [
              '9',
              'Fill **Pressure** `1.013` (**bar**), **Temperature** `30` (**°C**), **Flow Rate** `98` (**m³/hr**), **ΔP (Pressure Drop)** `0.05` (**bar**)',
              'Units shown beside each. Note the valve sheet works in **bar** and **m³/hr**, while the instrument sheet works in **mbar** and **kg/hr**',
            ],
            ['10', 'Click **Create**', 'The row appears with all ten columns filled'],
            [
              '11',
              '**Round trip:** click the pencil',
              '**Edit Valve** with **all thirteen** typed values exactly as entered — including P&ID No. and End Connection, which are not shown in the table',
            ],
            [
              '12',
              'Confirm both dropdowns came back on their saved value, not on the first item in the list',
              '**BUTTERFLY** and **FLANGED**, not whatever happens to be first',
            ],
            ['13', 'Without changing anything, click **Update**, reopen', 'Everything unchanged'],
            ['14', 'Change only the **ΔP** and **Update**', 'Only that column moves'],
            [
              '15',
              'Add a second valve with only Valve Tag filled, then reopen it',
              'The blank fields come back blank',
            ],
            [
              '16',
              'Delete the second one (trash → **Delete**)',
              'Confirmation titled **Delete Valve**, then the row goes',
            ],
            ['17', 'Reload the page', '`BFV-101` survives intact'],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Cross-check with UAT-SSOT-06: your instrument `PIT-101` names `IV-101` as its instrument valve. Add a valve tagged `IV-101` and confirm nothing anywhere links the two automatically — they are matched by eye today.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: ['Saving with no Valve Tag — the tab must show **Valve tag is required**.'],
        },
      ],
    },
    {
      id: 'UAT-SSOT-08',
      title: 'Live updates between two people, and deleting a referenced record',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: "confirm two engineers can work on the same project's process data at once, and record what happens when a record that others point at is deleted.",
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you and a colleague, both able to open the same project.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires stream `SW1`, the line that names `SW1` as its Input Data Tag, and equipment `MED-E1` that names `SW1` as an inlet stream.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Both of you open **Process Data (SSOT)** and select the **same project**, both on **Streams**',
              'Both see the same rows',
            ],
            [
              '2',
              'You add a new stream. Your colleague watches their screen **without reloading**',
              'The new row appears on their screen within a few seconds, on its own',
            ],
            [
              '3',
              "Your colleague edits that stream's temperature. You watch **without reloading**",
              'Your row updates on its own, and the density and enthalpy update with it',
            ],
            ['4', 'Your colleague deletes it. You watch', 'Your row disappears on its own'],
            [
              '5',
              'Both of you open the **same stream** in the edit dialog at the same time, change different fields, and both click **Update** — you first, colleague second',
              'Record which set of changes survives',
            ],
            [
              '6',
              'Now delete stream `SW1` (trash → **Delete**)',
              '⚠ known issue — it deletes with no warning at all, even though a line and a piece of equipment name it. Do not file this',
            ],
            [
              '7',
              "Go to the **Lines** tab and look at your line's **Input Tag** column",
              '⚠ known issue — it still reads `SW1`, pointing at a stream that no longer exists. Nothing flags it',
            ],
            [
              '8',
              "Go to the **Equipment** tab and look at `MED-E1`'s **Inlet Streams**",
              '⚠ known issue — still lists `SW1`',
            ],
            [
              '9',
              'Recreate a stream tagged `SW1` with the same values',
              'The line and equipment "reconnect" simply because the text matches again',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'All six tabs update live, not just Streams. Try the same two-person check on **Lines** and on **Valves**.',
          ],
        },
      ],
    },
    {
      id: 'UAT-SSOT-09',
      title: 'Permission checks and the Export Excel button',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm someone who may read process data cannot change it, and that someone with no thermal permission cannot reach the module.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you, plus a second sign-in with **View Thermal Desalination** but **not** Manage Process Data (SSOT).',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'ask an admin to set up the limited account and have that person sign out and back in.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'As the **limited user**, go to **ENGINEERING DATA → Process Data (SSOT)**',
              'The page opens; the project picker and all six tabs work; data is readable',
            ],
            [
              '2',
              'On the **Streams** tab, click **Add Stream**, fill it in and click **Create**',
              'The save is refused. ⚠ known issue — the message reads only "Failed to save stream. Please try again.", which does not tell you it was a permission problem. Do not file the wording',
            ],
            [
              '3',
              'Try the pencil on an existing stream, change something, click **Update**',
              'Refused the same way; the row on the table is unchanged',
            ],
            [
              '4',
              'Try the trash icon on a stream and confirm **Delete**',
              'Refused; the row is still there. ⚠ same generic wording',
            ],
            [
              '5',
              'Repeat steps 2–4 once on **Equipment**, **Lines**, **Instruments**, **Valves** and **Pipe Table**',
              'All six tabs refuse writes for this user',
            ],
            [
              '6',
              'Reload the page and check every tab',
              'Nothing the limited user attempted actually saved',
            ],
            [
              '7',
              'As **yourself** (with Manage Process Data), pick a project you are **not assigned to**, if one is visible, and try to add a stream',
              'The save is refused, for the same reason — being assigned to the project is required, not just the permission',
            ],
            [
              '8',
              'Have an admin remove **View Thermal Desalination** from the limited account; sign out and back in',
              '',
            ],
            [
              '9',
              'Go to **Process Data (SSOT)** again',
              'Either the sidebar entry is gone, or the page shows **Access Denied** — "You do not have permission to access the Process Data (SSOT) module"',
            ],
            [
              '10',
              'Also try **SALES & ESTIMATION → Thermal Calculators** with that same account',
              'The calculators still open — they are available to every signed-in user and do not need this permission',
            ],
            ['11', "Restore the account's permissions afterwards", ''],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'A read-only user changing any process data by any route, on any of the six tabs.',
            'Editing process data on a project you are not assigned to.',
          ],
        },
      ],
    },
  ],
  gaps: [
    {
      text: '**The Role filter offers "Supplier" but nothing can ever match it.** The create form only offers Vendor, Customer and Partner, so the Supplier filter always returns an empty list.',
    },
    {
      text: '**A duplicate entity *name* is only caught after you click Create Entity.** The live duplicate check while you type covers email, PAN and GSTIN only. The record is still refused — just later than you would expect.',
    },
    {
      text: "**Changing an entity's GSTIN does not update the GSTIN printed on existing purchase orders.** Changing the name or the email does propagate; the GSTIN does not.",
    },
    {
      text: '**Export Excel on Process Data does nothing.** The button shows "Excel export coming soon" and no file is produced.',
    },
    {
      text: '**Nothing stops you deleting a stream that a line or a piece of equipment still points at.** There is no warning and no cascade — the line keeps a tag pointing at a record that no longer exists, and nothing anywhere flags it.',
    },
    {
      text: '**A refused save in Process Data looks exactly like a network failure.** Whatever the reason — no permission, not assigned to the project, connection lost — the message is the generic "Failed to save …" / "Failed to delete …".',
    },
    {
      text: '**There is no separate "edit entities" permission.** Anyone who can create an entity can also edit, archive and restore any entity. If you want someone to be able to add vendors but not change existing ones, that is not possible today.',
    },
    {
      text: '**Entity edits are saved straight from your browser.** Creation goes through a checked server-side route; edits do not. It works, but it means the duplicate checks that guard creation do not guard an edit — you can rename an entity to clash with another one.',
    },
    {
      text: '**Deleting a saved calculation happens instantly, with no "are you sure".** One mis-click on the bin icon in the load list and the case is gone.',
    },
    {
      text: '**Two older calculator pages, Heat Transfer and Heat Duty, still exist but are not listed on the hub.** The hub deliberately points you at the unified **Heat Exchanger Calculator** instead. If you find a link to either of the old ones anywhere in the app, that is worth reporting.',
    },
  ],
};

export default entitiesGuide;
