// GENERATED by scripts/generate-workflow-guide.mjs — do not edit by hand.
// Source: docs/workflows/user-testing/uat-hr-and-flow.md
import type { WorkflowGuideModule } from './types';

export const flowGuide: WorkflowGuideModule = {
  id: 'flow',
  label: 'Flow — Tasks & Meetings',
  intro: [
    {
      section: 'What this module does',
      blocks: [
        {
          k: 'p',
          text: '**HR & Leave** runs the people side of the business: the employee directory and profiles, the company holiday calendar, leave applications and their two-step approval, the leave balances that go up and down as leave is taken, compensatory leave earned by working on a holiday, and travel expense claims with receipts.',
        },
        {
          k: 'p',
          text: '**Flow** is the daily-work side: your personal task list, tasks assigned to you by other people, meeting minutes that turn action items into real tasks, a team board showing what everyone is working on, and the **Inbox** where every approval request and status change from every module lands.',
        },
        {
          k: 'p',
          text: "The two are joined by notifications. Almost every HR action creates an item in somebody else's Inbox, and several also send an email. Testing those properly needs two people.",
        },
      ],
    },
    {
      section: 'Before you start',
      blocks: [
        {
          k: 'h',
          text: 'Permissions you need',
        },
        {
          k: 'table',
          steps: false,
          head: ['What you want to test', 'Permission needed'],
          rows: [
            ['Apply for leave, on-duty, travel expenses', 'None — open to every signed-in user'],
            ['Employee directory, holidays (view), Flow', 'None — open to every signed-in user'],
            [
              'Approve / reject leave and on-duty',
              '**Approve Leaves**, *and* you must be on the HR approver list (see below)',
            ],
            ['Team Requests tab, Team Calendar, Leave Summary', '**Approve Leaves**'],
            ['Add / edit / delete holidays, declare a working day', '**Manage HR Settings**'],
            ['Open the Edit Profile button on an employee', '**Manage Users**'],
            ['Actually save an employee profile edit', '**Manage HR Profiles**'],
            ['Administration → HR Setup (leave types, balances)', '**Manage Users**'],
          ],
        },
        {
          k: 'p',
          text: 'Permission changes take a few minutes to reach someone already signed in. Have them sign out and back in before reporting a permission problem.',
        },
        {
          k: 'h',
          text: 'Test data you need first',
        },
        {
          k: 'ul',
          items: [
            '**Leave types and balances must exist for the current year.** If the Leaves page shows *"No leave balances found"*, run **UAT-HR-03** first — nothing else in the leave section will work.',
            '**At least two company holidays** in the current year, one of them in the future (needed for on-duty). Create them in **UAT-HR-04**.',
            '**A receipt file** (PDF or photo, under 5 MB) with a vendor name, a date, an amount and ideally a GST breakdown — for the receipt-parsing test.',
            '**An approver list configured in HR settings.** There is **no screen in the app for this** — the list of people who can approve leave, on-duty and travel expenses is set directly in the database. Confirm with the developer that at least two approvers are configured before you start, otherwise **Submit for Approval** fails with *"Leave approvers not configured"* or *"No approvers configured. Please contact HR."*',
          ],
        },
        {
          k: 'h',
          text: 'A second user — read this before you start',
        },
        {
          k: 'p',
          text: 'Yes, several tests need one. Leave and on-duty need **two approvals**, so you may need a third sign-in for the full path.',
        },
        {
          k: 'table',
          steps: false,
          head: ['Account', 'What it needs', 'Used by'],
          rows: [
            ['**Your account** (applicant)', 'Nothing special', 'Everything'],
            [
              '**Approver A**',
              '**Approve Leaves** *and* be on the configured HR approver list',
              'UAT-HR-07, 08, 11, 14, 15, 20, UAT-FLOW-08, 09',
            ],
            [
              '**Approver B**',
              'Same as Approver A — a *different* person, needed to complete a two-step leave/on-duty approval',
              'UAT-HR-07, UAT-HR-14',
            ],
            [
              '**A limited user**',
              'No **Manage HR Settings**, no **Approve Leaves**',
              'UAT-HR-11, UAT-HR-04',
            ],
            [
              '**An admin**',
              '**Manage Users** + **Manage HR Profiles** + **Manage HR Settings**',
              'UAT-HR-02, 03, 04, 13',
            ],
          ],
        },
        {
          k: 'p',
          text: 'Wherever a step needs the other person, it is written as **"as Approver A, sign in and…"**. If the applicant happens to also be on the approver list, the app drops them out of the approver set and then only **one** approval is needed — the leave detail page says so explicitly.',
        },
        {
          k: 'p',
          text: '**Sidebar:** HR lives under **SETUP → HR & Leave**. Flow lives under **DAILY OPERATIONS → Flow**. Leave types and yearly balance setup live under **ADMINISTRATION → HR Setup**.',
        },
        {
          k: 'p',
          text: '**Read the [Known issues in this module](#known-issues-in-this-module) section at the bottom before you start.** Nine things in this module are already known to be broken or missing; do not spend time filing them again.',
        },
      ],
    },
  ],
  workflows: [
    {
      id: 'UAT-FLOW-01',
      title: 'Create and assign a task — round-trip check',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'create a task with every field filled, assign it to someone else, and confirm it arrives on their list intact.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you and any colleague.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'know one real project name.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Sidebar → **DAILY OPERATIONS → Flow**',
              'The **Flow** landing page with **Daily Work** (My Tasks, Inbox) and **Collaboration** (Team Board, Meeting Minutes, Portfolio Review)',
            ],
            ['2', 'Click **My Tasks** → **New Task**', 'A dialog **New Task**'],
            ['3', 'Note who is pre-filled in **Assignee**', 'Yourself'],
            [
              '4',
              'Fill **Title** and **Description**, change **Assignee** to a colleague, pick a **Project**, set **Priority** to **Urgent**, and set a **Due Date** two days out',
              'All six accepted; the assignee list shows names with their department',
            ],
            ['5', 'Click **Create Task**', 'A green "Task created" message; the dialog closes'],
            [
              '6',
              'Look at **My Tasks**',
              'The task is **not** in your list — it belongs to the person you assigned it to',
            ],
            [
              '7',
              'Ask the colleague to open **Flow → My Tasks**',
              'The task appears **without them reloading the page** — the list is live',
            ],
            [
              '8',
              'Have them read the card',
              'Title in bold (Urgent tasks are heavier), the description underneath, then chips for **URGENT**, their own name, the due date, and the project name',
            ],
            [
              '9',
              'Have them confirm every value matches what you typed',
              'Title, description, priority, due date, project and assignee all exactly as entered',
            ],
            [
              '10',
              'Create a second task assigned to **yourself** with **no** description, **no** project and **no** due date',
              'Created cleanly; the card shows only the title, the priority chip and your name — no empty chips',
            ],
            [
              '11',
              'Reload your **My Tasks** page',
              'Both the task you kept and its values survive the reload',
            ],
            [
              '12',
              "Try to change a task's title, assignee, due date or priority after creating it",
              '⚠ known issue — there is **no edit form for a task**. You can only change its status or delete it. Do not file this',
            ],
            [
              '13',
              'From the Flow landing page, click the **New Task** action in the header',
              'The same **New Task** dialog opens',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'A due date **in the past** should show as a red **"n d overdue"** chip; one set to today should read **Due today**, tomorrow **Due tomorrow**.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Assigning a task to a deactivated user — they must not appear in the Assignee list, and the save must be refused if forced.',
            'Creating a task with an empty title — the **Create Task** button stays greyed out.',
          ],
        },
      ],
    },
    {
      id: 'UAT-FLOW-02',
      title: 'Move a task through its life, and delete one',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the status control works, terminal states lock, and only the creator can delete.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you and a colleague.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires both tasks from UAT-FLOW-01.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'On your own task card, hover the circle icon on the left',
              'A tooltip reading **Mark as in_progress**',
            ],
            [
              '2',
              'Click it',
              'The icon turns into a blue play symbol; the **In Progress** tab count goes up by one and **Todo** down by one',
            ],
            [
              '3',
              'Click the icon again',
              'A green tick; the title is struck through; the card fades; **Done** count goes up',
            ],
            [
              '4',
              'Hover the icon on the completed task',
              'Tooltip reads **Completed** and the control is disabled — **Done** is the end of the line',
            ],
            [
              '5',
              'Look for the bin icon on the completed task',
              'Gone — completed tasks cannot be deleted from the card',
            ],
            ['6', 'Click the **Done** tab', 'Your completed task is listed there'],
            [
              '7',
              'Click the **All** tab',
              'Todo, In Progress and Done tasks all appear; the count chip matches the number of cards',
            ],
            [
              '8',
              'Create a fresh task for yourself. Try to move it from **In Progress** back to **Todo**',
              '⚠ known issue — the control only steps forward. There is no way back to Todo and no way to cancel a task. Do not file this',
            ],
            [
              '9',
              'On a task you created but assigned to your colleague, click the bin icon',
              'A "Task deleted" message; the task disappears from their list too',
            ],
            [
              '10',
              'Ask the colleague to create a task **for you**, then try to delete it from your list',
              'Refused with a message about only the creator being able to delete',
            ],
            [
              '11',
              'Ask the colleague to move that task to **In Progress** from their side',
              'Your list updates within a couple of seconds without a reload',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Deleting a task somebody else created.',
            'Changing the status of a task you neither created nor are assigned to.',
            'Any status change on a task that is already **Done**.',
          ],
        },
      ],
    },
    {
      id: 'UAT-FLOW-03',
      title: 'Team Board',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the team-wide view shows who is working on what.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you and a colleague, each with at least one open task.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires UAT-FLOW-01.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Flow → **Team Board**',
              'A page titled **Team Board** and a line reading "*n* active tasks across *m* members"',
            ],
            [
              '2',
              'Find yourself and your colleague',
              'Each with their own Todo and In Progress counts and their open tasks listed',
            ],
            [
              '3',
              'Compare your own block against your **My Tasks** page',
              'The same open tasks, with the same priority chips',
            ],
            [
              '4',
              'Confirm **completed** tasks are not shown',
              'Only Todo and In Progress appear here',
            ],
            ['5', 'Search for a colleague by name', 'The board narrows to them'],
            [
              '6',
              'Have the colleague mark one of their tasks **Done**',
              'Within a couple of seconds it disappears from the board and the header count drops by one',
            ],
          ],
        },
      ],
    },
    {
      id: 'UAT-FLOW-04',
      title: 'Record meeting minutes and save as a draft',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'capture a meeting with action items and keep it as a draft.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone. Pick two colleagues to be attendees.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'nothing.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Flow → **Meeting Minutes** → **New Meeting**',
              'A two-step form: **Meeting Details**, then **Action Items**',
            ],
            [
              '2',
              'Fill **Meeting Title**, **Date**, **Duration (min)**, **Location**',
              'All accepted',
            ],
            ['3', 'Add two **Attendees**', 'Each appears as a chip with an avatar'],
            [
              '4',
              'Fill **Agenda** and **Notes** with several lines each',
              'Both accept multi-line text',
            ],
            [
              '5',
              'Try to continue before setting a title, date or attendee',
              '**Next: Action Items** stays greyed out until all three are filled',
            ],
            [
              '6',
              'Click **Next: Action Items**',
              'A table with columns Description, Action, Responsible Person, Due Date, Priority',
            ],
            [
              '7',
              'Fill a first row completely, choosing a **Responsible Person** from the attendee list',
              'The Responsible Person dropdown offers your attendees',
            ],
            [
              '8',
              'Click **Add Row** and fill a **Description only**, leaving Action blank',
              'That row is highlighted in red and the Action cell shows **Required**',
            ],
            [
              '9',
              'Fill in the Action but leave Responsible Person blank',
              'The row stays highlighted',
            ],
            [
              '10',
              'Complete the second row, then add a **third** row and leave it entirely blank',
              'The blank row is not flagged — it will simply be ignored',
            ],
            [
              '11',
              'Click the bin on the blank row',
              'It is removed. The bin on the **last remaining** row must be disabled',
            ],
            [
              '12',
              'Click **Save as Draft**',
              '"Meeting saved as draft"; you land on the meeting page with a **Draft** chip',
            ],
            [
              '13',
              'Read the page',
              'Title, date written out in full, duration and location on one line; attendee chips; Agenda and Notes exactly as typed',
            ],
            [
              '14',
              'Read the **Action Items** table',
              'Both complete rows, with Description, Action, Responsible, Due Date and Priority as entered',
            ],
            [
              '15',
              'Go back to **Meeting Minutes**',
              'Your meeting is listed with a **Draft** chip, the date, the duration, the attendee count and your name',
            ],
            [
              '16',
              'Try to change the title, attendees, agenda, notes or an action item',
              '⚠ known issue — a draft meeting **cannot be edited** after saving, and no action items can be added on the detail page. Do not file this',
            ],
          ],
        },
      ],
    },
    {
      id: 'UAT-FLOW-05',
      title: 'Finalize a meeting — action items become real tasks',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: "confirm finalizing turns every actionable item into a task on the right person's list, and that the meeting then locks.",
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you and the two attendees.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires the **Draft** meeting from UAT-FLOW-04 with two actionable rows.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Open the draft meeting',
              'The header shows **Delete** and **Finalize (2 tasks)** — the count matching your actionable rows',
            ],
            [
              '2',
              'Click **Finalize (2 tasks)**',
              'A message *"Meeting finalized — 2 tasks created"*; the chip changes from **Draft** to **Finalized**',
            ],
            [
              '3',
              'Read the Action Items table again',
              'A new **Task Status** column, each row showing the live status of its generated task (starting at **Todo**)',
            ],
            [
              '4',
              'Ask the first attendee to open **Flow → My Tasks**',
              'A new task whose title is the **Action** text from their row, with the due date and priority from the table',
            ],
            [
              '5',
              'Ask the second attendee the same',
              "Their own row's task is on their list — not on the first attendee's",
            ],
            [
              '6',
              'Confirm the rows that were **not** actionable did not generate a task',
              'Only rows with both an Action and a Responsible Person become tasks',
            ],
            [
              '7',
              'Have the first attendee move their task to **In Progress**',
              'Back on the meeting page (reload it), the **Task Status** for that row now reads **In Progress**',
            ],
            ['8', 'Have them mark it **Done**', 'On reload, the meeting row reads **Done**'],
            [
              '9',
              "Look at the finalized meeting's header",
              '**Delete** and **Finalize** are gone; instead there is **Start next review**',
            ],
            [
              '10',
              'Read the footer of the page',
              '*"Created by …"* and *"Finalized on …"* with the right date',
            ],
            [
              '11',
              'Click **Start next review**',
              '*"Next review meeting created"* and you land on a new **Draft** meeting',
            ],
            [
              '12',
              'On the new meeting, click **Previous review**',
              'You are taken back to the finalized one',
            ],
            [
              '13',
              'Return to the finalized meeting and click **Start next review** again',
              'It reads **Open next review** and takes you to the meeting already created — it does not create a second one',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Finalizing the same meeting twice.',
            'Editing or deleting a meeting once it is **Finalized**.',
            'A meeting finalizing "half way" — if it fails, no tasks at all should have been created. If you see a partial result, report it immediately.',
          ],
        },
      ],
    },
    {
      id: 'UAT-FLOW-06',
      title: 'Meeting guards — delete, empty finalize, terminal state',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the guards around meetings.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you and a colleague who was **not** an attendee.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires UAT-FLOW-04 and UAT-FLOW-05.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Create a new meeting, fill step 1, and go to step 2 without completing any row',
              '**Finalize** stays greyed out — at least one row needs both an Action and a Responsible Person',
            ],
            [
              '2',
              '**Save as Draft** anyway',
              'Saved; the meeting page shows *"No action items yet."* and **Finalize (0 tasks)** disabled',
            ],
            [
              '3',
              'Click **Delete** on that draft',
              'A confirmation naming the meeting and warning it cannot be undone',
            ],
            ['4', 'Click **Cancel**', 'Nothing happens'],
            [
              '5',
              'Click **Delete** again and confirm',
              '"Meeting deleted"; you are returned to the Meeting Minutes list and it is gone',
            ],
            [
              '6',
              'Ask the **non-attendee colleague** to open the finalized meeting from UAT-FLOW-05',
              'They can read it; they must not be offered Delete or Finalize on a draft they are not part of',
            ],
            [
              '7',
              'Create a draft meeting naming a **deactivated user** as a Responsible Person, then finalize',
              'Refused, naming the inactive person. (Skip this step if you have no deactivated user)',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Deleting a meeting you did not create.',
            'Finalizing a meeting with no complete action item.',
            'Finalizing a meeting that names a deactivated person as responsible.',
          ],
        },
      ],
    },
    {
      id: 'UAT-FLOW-07',
      title: 'Work the Inbox — filter, search, complete',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the Inbox gathers work from every module and that clearing an item works.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you and **Approver A** (whose Inbox will have HR items in it from earlier tests).',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'works best after UAT-HR-07, UAT-HR-14 and UAT-HR-19 have created real notifications.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Flow → **Inbox**',
              'A page titled **Inbox** with a count in the top right, a search box, and filter chips',
            ],
            [
              '2',
              'Read the filter chips',
              'Only chips that actually have items are shown, each with its count in brackets; **All** is always there',
            ],
            [
              '3',
              'Click **HR**',
              'Only HR items remain, and the count matches the number of cards',
            ],
            ['4', 'Click **Approvals**', 'Only the items that need a decision from you'],
            [
              '5',
              "Click **All**, then type part of a colleague's name into the search box",
              'The list narrows to notifications from or about them — search covers the title, message and sender',
            ],
            [
              '6',
              'Clear search. Read one card',
              'A priority flag, the title, a two-line message preview, who raised it, how long ago, and an **Action Required** chip if it needs a decision',
            ],
            [
              '7',
              'Click a card that has a link',
              'You are taken to the record it is about — the leave request, on-duty request or expense report',
            ],
            [
              '8',
              'Return to the Inbox. Click the small open-in-new-tab icon on a card',
              'The same record opens in a new tab, and the Inbox stays where it was',
            ],
            [
              '9',
              'Find a card with a green **Complete** button and click it',
              'The card disappears **immediately**, and a "Task completed" message appears',
            ],
            ['10', 'Reload the page', 'The completed card is still gone — it really saved'],
            [
              '11',
              'Filter down to a chip with nothing in it (or clear everything)',
              '*"No pending notifications. All caught up!"*',
            ],
            [
              '12',
              'Compare against the **HR & Leave** sidebar badge',
              'The number of pending HR approvals in the badge matches the HR items awaiting you',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Completing a notification addressed to somebody else.',
            'A completed item reappearing after a reload.',
          ],
        },
      ],
    },
    {
      id: 'UAT-FLOW-08',
      title: 'Notifications end to end, and the ones that clear themselves',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm every HR decision produces the right in-app notification for the right person, and that approver items close themselves once a decision is made.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you, **Approver A**, **Approver B**. Keep three browsers or three profiles open side by side if you can.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires UAT-HR-03 and a configured approver list. This test repeats parts of the earlier ones deliberately, from the notification angle.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Submit a leave request',
              '**Both** approvers get a card **Leave Request: &lt;your name&gt;** with an **Action Required** chip',
            ],
            ['2', 'Check your own Inbox', 'You get nothing for your own submission'],
            [
              '3',
              '**As Approver A, sign in** and approve once',
              'You (the employee) get **Leave Request Partially Approved**',
            ],
            [
              '4',
              "Check Approver A's Inbox",
              "Their own card has closed; Approver B's is still open",
            ],
            ['5', '**As Approver B, sign in** and approve', 'You get **Leave Request Approved**'],
            [
              '6',
              "Check **both** approvers' Inboxes",
              'Both action cards have closed on their own — nobody had to tick them off',
            ],
            [
              '7',
              'Ask a colleague who is **not** an approver to check their Inbox',
              'They have a **Team Leave Notice** informational card naming you and the dates',
            ],
            [
              '8',
              'Submit a second leave request and have Approver A **reject** it',
              "You get **Leave Request Rejected** with the reason; both approvers' action cards close",
            ],
            [
              '9',
              'Submit a third and **cancel it yourself**',
              "Both approvers' action cards close without either of them doing anything",
            ],
            [
              '10',
              'Submit an on-duty request',
              'Both approvers get **On-Duty Request: &lt;your name&gt;**',
            ],
            [
              '11',
              'Have both approve it',
              'You get **On-Duty Request Approved** mentioning the comp-off day; the team gets **Team On-Duty Notice**',
            ],
            [
              '12',
              'Submit a travel expense claim',
              'Every configured expense approver gets **Travel Expense: TE-…** with the amount in rupees',
            ],
            [
              '13',
              'Have one of them **Return** it',
              'You get **Travel Expense Report Returned for Revision**, quoting their comment',
            ],
            ['14', 'Resubmit and have it approved', 'You get **Travel Expense Report Approved**'],
            [
              '15',
              'Assign a Flow task to a colleague',
              'Their **My Tasks** list updates live. Note whether they also get anything in their **Inbox** — Flow tasks are not expected to produce an inbox item',
            ],
            [
              '16',
              'Finalize a meeting with an action item for a colleague',
              'Their **My Tasks** list gains the task. Again, note what (if anything) lands in their Inbox',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Notification counts in the sidebar badge fall as you clear items, and never go negative.',
            'A card you have already actioned never reappears after a reload.',
          ],
        },
      ],
    },
    {
      id: 'UAT-FLOW-09',
      title: 'Emails that should arrive alongside the in-app notification',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the emails actually land in a real inbox, with a readable subject and the right details. **Check your email client, not the app.**',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you and **Approver A**. You each need access to the mailbox registered against your account.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires UAT-HR-03. Emails can take a minute or two — wait before recording a failure, and check the spam folder.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see **in your email inbox**'],
          rows: [
            [
              '1',
              'Submit a leave request',
              'An email subject **Leave Request: &lt;your name&gt;**, listing Employee, Type, From, To, Days and Reason, with a link into the app',
            ],
            ['2', 'Open the link in that email', 'It takes you to the Leaves page in the app'],
            [
              '3',
              '**As Approver A, sign in** and approve once (status **Partially Approved**)',
              'The **remaining** approver receives an email subject **Leave Pending Your Approval: &lt;your name&gt;**, showing "1 of 2 approvals"',
            ],
            [
              '4',
              'Confirm the approver who already approved does **not** get that one',
              'Only the outstanding approver is chased',
            ],
            [
              '5',
              'Complete the second approval',
              'An email subject **Leave Approved: &lt;your name&gt;** arrives, and **your own mailbox is on it**',
            ],
            [
              '6',
              'Submit and reject another leave request',
              'An email subject **Leave Rejected: &lt;your name&gt;**, again copying you',
            ],
            [
              '7',
              'Submit a travel expense claim',
              'An email subject **Travel Expense Submitted: TE-2026-nnnn** with Report #, Employee, Purpose and Amount',
            ],
            [
              '8',
              'Have it approved',
              '**You** (the employee) receive **Travel Expense Approved: TE-2026-nnnn** — not the person who approved it',
            ],
            [
              '9',
              'Have another claim rejected',
              '**Travel Expense Rejected: TE-2026-nnnn** in your mailbox',
            ],
            [
              '10',
              'Submit an on-duty request and take it through to approval',
              '⚠ known issue — **no on-duty email is ever sent**, at any stage, to anyone. Do not file this',
            ],
            [
              '11',
              'Approve the same leave request twice in quick succession (double-click)',
              'Only **one** email of each kind arrives — no duplicates',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Amounts in the emails are formatted in rupees and match the app exactly.',
            'Dates in the emails match the dates on screen — not a day out.',
          ],
        },
      ],
    },
    {
      id: 'UAT-FLOW-10',
      title: 'Threads and @mentions',
      knownIssue: true,
      blocks: [
        {
          k: 'note',
          text: '⚠ **Known issue — expected to fail.** Discussion threads on notifications and @mentions of colleagues are built but are **not reachable from any page in the app**. There is no comment box, no mentions list and no mention badge. Do not file feedback for this; it is already on the fix list. Run the test only to confirm nothing has changed.',
          warn: true,
        },
        {
          k: 'meta',
          label: 'Goal',
          text: 'record that the collaboration layer on notifications is not yet wired up.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires at least one notification in your Inbox.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Flow → **Inbox**, open a notification card',
              '⚠ known issue — no comment box, no thread panel, no discussion of any kind',
            ],
            [
              '2',
              'Look for a comment or message count on any card',
              '⚠ known issue — none appears',
            ],
            [
              '3',
              'Look anywhere in Flow for a **Mentions** view or an unread-mentions badge',
              '⚠ known issue — neither exists',
            ],
            [
              '4',
              "Type `@` followed by a colleague's name in any Flow text box (task description, meeting notes)",
              'The text is stored as plain text; nobody is notified',
            ],
          ],
        },
      ],
    },
  ],
  gaps: [
    {
      text: '**Threads and @mentions are unreachable.** The discussion layer on notifications exists but no page shows it.',
    },
    {
      text: '**On-duty emails never send.** In-app notifications work; email does not, at any stage.',
    },
    {
      text: '**Tasks cannot be edited, moved backwards or cancelled.** The status control only steps Todo → In Progress → Done.',
    },
    {
      text: '**A draft meeting cannot be edited** after saving, and no action item can be added on the meeting page.',
    },
  ],
};

export default flowGuide;
