// GENERATED by scripts/generate-workflow-guide.mjs — do not edit by hand.
import type { WorkflowGuideModule } from './types';

export type { WorkflowGuideModule, WorkflowCase, WorkflowBlock } from './types';

export interface WorkflowGuideSummary {
  id: string;
  label: string;
  workflows: number;
  gaps: number;
}

/** Counts only — the content itself is loaded on demand. */
export const WORKFLOW_GUIDE_SUMMARY: Record<string, WorkflowGuideSummary> = {
  proposals: {
    id: 'proposals',
    label: 'Enquiries, Proposals & Projects',
    workflows: 30,
    gaps: 7,
  },
  procurement: {
    id: 'procurement',
    label: 'Procurement',
    workflows: 34,
    gaps: 6,
  },
  accounting: {
    id: 'accounting',
    label: 'Accounting',
    workflows: 37,
    gaps: 4,
  },
  documents: {
    id: 'documents',
    label: 'Document Control',
    workflows: 18,
    gaps: 12,
  },
  materials: {
    id: 'materials',
    label: 'Estimation & Catalogs',
    workflows: 27,
    gaps: 17,
  },
  entities: {
    id: 'entities',
    label: 'Entities & Process Data',
    workflows: 21,
    gaps: 10,
  },
  thermal: {
    id: 'thermal',
    label: 'Thermal Calculators',
    workflows: 7,
    gaps: 2,
  },
  hr: {
    id: 'hr',
    label: 'HR & Leave',
    workflows: 21,
    gaps: 9,
  },
  flow: {
    id: 'flow',
    label: 'Flow — Tasks & Meetings',
    workflows: 10,
    gaps: 4,
  },
  admin: {
    id: 'admin',
    label: 'Administration',
    workflows: 25,
    gaps: 6,
  },
};

/** Lazily loads one section's content so the guide bundle stays small. */
export const WORKFLOW_GUIDE_LOADERS: Record<string, () => Promise<WorkflowGuideModule>> = {
  proposals: () => import('./proposals').then((m) => m.proposalsGuide),
  procurement: () => import('./procurement').then((m) => m.procurementGuide),
  accounting: () => import('./accounting').then((m) => m.accountingGuide),
  documents: () => import('./documents').then((m) => m.documentsGuide),
  materials: () => import('./materials').then((m) => m.materialsGuide),
  entities: () => import('./entities').then((m) => m.entitiesGuide),
  thermal: () => import('./thermal').then((m) => m.thermalGuide),
  hr: () => import('./hr').then((m) => m.hrGuide),
  flow: () => import('./flow').then((m) => m.flowGuide),
  admin: () => import('./admin').then((m) => m.adminGuide),
};
