// GENERATED by scripts/generate-workflow-guide.mjs — do not edit by hand.
// Source: docs/workflows/user-testing/uat-entities-ssot-thermal.md
import type { WorkflowGuideModule } from './types';

export const thermalGuide: WorkflowGuideModule = {
  id: 'thermal',
  label: 'Thermal Calculators',
  intro: [
    {
      section: 'What this module does',
      blocks: [
        {
          k: 'p',
          text: "**Entity Management** is the company's master list of everyone we do business with — vendors, customers and partners. Each entity carries its contact people, billing and shipping addresses, PAN and GSTIN, bank accounts, credit terms and an opening balance carried forward from the previous year. Every purchase order, bill, invoice and payment in the app points back to one of these records, so a mistake here spreads everywhere.",
        },
        {
          k: 'p',
          text: '**Process Data (SSOT)** is the per-project engineering master used to build P&IDs and datasheets. For a chosen project it holds the **Streams** (the fluids and their conditions), the **Equipment** they flow through, the **Lines** (pipes, with automatic sizing), the **Instruments** and **Valves** on those lines, and a **Pipe Table** of standard sizes used when sizing a line. Records are linked to each other by tag text — exactly the way the source engineering spreadsheets are keyed.',
        },
        {
          k: 'p',
          text: '**Thermal Calculators** is a suite of around thirty standalone design calculators for MED / MED-TVC / MSF desalination plants, plus a full **MED Plant Designer** wizard, a **Flash Chamber Calculator**, and a read-only **Reference Projects** library of as-built plant data. Most calculators compute as you type; most let you save a named set of inputs and load it back later.',
        },
      ],
    },
    {
      section: 'Before you start',
      blocks: [
        {
          k: 'h',
          text: 'Permissions you need',
        },
        {
          k: 'table',
          steps: false,
          head: ['What you want to test', 'Permission needed'],
          rows: [
            ['Open Entity Management, see the list and View Details', '**View Entities**'],
            [
              'New Entity, Edit Entity, Archive, Unarchive',
              '**Create Entities** (there is no separate "edit" permission)',
            ],
            ['**View Ledger** on an entity row', '**View Accounting**'],
            ['Open Process Data (SSOT) and read all six tabs', '**View Thermal Desalination**'],
            [
              'Add / edit / delete anything in Process Data',
              '**Manage Process Data (SSOT)** *and* you must be assigned to the project you are editing',
            ],
            [
              'Open Thermal Calculators, run and save calculations',
              'None — open to every signed-in user',
            ],
          ],
        },
        {
          k: 'p',
          text: 'Permission changes take a few minutes to reach someone who is already signed in. Have them sign out and back in before reporting a permission problem.',
        },
        {
          k: 'h',
          text: 'Test data you need first',
        },
        {
          k: 'ul',
          items: [
            '**A project you are assigned to.** Everything in Process Data hangs off a project chosen from the **Select Project** dropdown, and you cannot save anything on a project you are not assigned to. Sort this out before starting the SSOT tests.',
            '**A note pad, physical or otherwise.** The round-trip tests (UAT-ENT-03, and one per Process Data record type) ask you to write down every value you typed and compare it after saving. Do not trust memory — the whole point of the test is spotting a single field that silently changed.',
            '**A vendor with at least one purchase order against it** for UAT-ENT-11, and **a vendor or customer with a few posted transactions** for UAT-ENT-10.',
            '**A calculator or two you know the answer to.** For the thermal sweep, being able to say "that number is about right for a plant this size" is worth far more than confirming a number appeared.',
          ],
        },
        {
          k: 'h',
          text: 'A second user — read this before you start',
        },
        {
          k: 'p',
          text: 'Three tests need one.',
        },
        {
          k: 'table',
          steps: false,
          head: ['Account', 'What it needs', 'Used by'],
          rows: [
            ['**A limited user**', '**View Entities** but **not** Create Entities', 'UAT-ENT-12'],
            [
              '**A limited user**',
              '**View Thermal Desalination** but **not** Manage Process Data (SSOT); or a user not assigned to your test project',
              'UAT-SSOT-09',
            ],
            [
              '**A colleague**',
              "Any account that can open the same project's Process Data",
              'UAT-SSOT-08',
            ],
            ['**A colleague**', 'Any signed-in account', 'UAT-THRM-05'],
          ],
        },
        {
          k: 'h',
          text: 'Sidebar',
        },
        {
          k: 'ul',
          items: [
            'Entities: **SETUP → Entity Management**',
            'Process Data: **ENGINEERING DATA → Process Data (SSOT)**',
            'Thermal: **SALES & ESTIMATION → Thermal Calculators**',
          ],
        },
        {
          k: 'p',
          text: '**Read the [Known issues in this module](#known-issues-in-this-module) section at the bottom before you start.** Eight things are already known to be broken or missing; please do not spend time filing them again.',
        },
        {
          k: 'h',
          text: 'A note for engineering testers',
        },
        {
          k: 'p',
          text: 'On every thermal and process-data test, "a number appeared" is not a pass. Check three things each time:',
        },
        {
          k: 'ol',
          items: [
            '**The unit is shown, and it is the unit you expected.** mbar vs bar and kg/s vs T/h are the two that bite.',
            '**The magnitude is physically plausible** for the plant you described. A 4-metre shell for a 100 m³/day unit is wrong even if it computes.',
            '**The result moves the right way when you change an input.** Double the flow and the pipe should get bigger, not smaller.',
          ],
        },
        {
          k: 'p',
          text: 'Anything that fails one of those three is worth a Feedback item even if nothing on screen looks like an error.',
        },
      ],
    },
  ],
  workflows: [
    {
      id: 'UAT-THRM-01',
      title: 'Tour the Thermal Calculators hub',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the calculator directory lists everything, search works, and every tile opens the tool it names.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone signed in.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'nothing.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Sidebar → **SALES & ESTIMATION → Thermal Calculators**',
              'A page headed **Thermal Calculators**',
            ],
            [
              '2',
              'Read the section headings down the page',
              '**Plant Design**, **Compression & Ejectors**, **Heat Exchange & Thermal**, **Fluid Systems & Equipment**, **Plant Auxiliaries**, **Properties & Lookups**',
            ],
            [
              '3',
              'Count the tiles',
              'Around thirty in total. Two of them — **Condenser** and **Ejector** — carry a **Coming Soon** chip',
            ],
            [
              '4',
              'Click a **Coming Soon** tile',
              'Nothing happens, or you are told it is not ready. It must not open a broken page',
            ],
            [
              '5',
              'Type `pipe` into **Search calculators...**',
              'The page narrows to matching tiles as you type; empty sections disappear',
            ],
            [
              '6',
              'Type something that matches nothing',
              '"No calculators match ..." rather than a blank page',
            ],
            [
              '7',
              'Clear the search. Switch the view toggle from card view to **list view**',
              'The same calculators as a compact list',
            ],
            ['8', 'Switch back to card view', 'Cards again'],
            [
              '9',
              'Open **Pipe Sizing**, then use the breadcrumb to come back',
              'You are back on the hub, and a **Recently Used** strip has appeared at the top with Pipe Sizing in it',
            ],
            [
              '10',
              'Open five more calculators, coming back each time',
              'Recently Used holds **at most five**, most recent first, and the oldest drops off',
            ],
            ['11', 'Reload the page', 'Recently Used survives the reload'],
            [
              '12',
              'Click every remaining tile in turn and note the page heading you land on',
              'Each heading matches the tile you clicked, and none shows an error or an endless spinner',
            ],
            [
              '13',
              'Type the old address `/thermal` into the browser directly',
              'You are sent to the Thermal Calculators hub — the old landing page no longer exists',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'The **Flash Chamber** and **Reference Projects** tiles sit in the **Plant Design** section, alongside the two MED tools. They are reached from the hub like everything else.',
          ],
        },
      ],
    },
    {
      id: 'UAT-THRM-02',
      title: 'MED Plant Designer end to end, with a save-and-reload check',
      knownIssue: false,
      blocks: [
        {
          k: 'note',
          text: 'This is the largest tool in the app. Work through it with a plant you actually know, so you can judge whether the answers are sensible rather than merely present.',
          warn: false,
        },
        {
          k: 'meta',
          label: 'Goal',
          text: 'design an MED plant from scratch, sanity-check the results, save the case, start over, reload it, and confirm every input **and** every headline result comes back identical.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone signed in.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'nothing. Have a notepad — you will be comparing about thirty inputs and a dozen results before and after the reload.',
        },
        {
          k: 'h',
          text: 'Part A — the inputs',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Hub → **Plant Design** → **MED Plant Designer**',
              'A page headed **MED Plant Designer** with a **Multi-Effect Distillation** chip, and a four-step strip: **Design Inputs**, **Equipment & Geometry**, **Detailed Design**, **Review & Export**',
            ],
            ['2', 'Note the three buttons at the top right', '**Load**, **Save**, **Start Over**'],
            [
              '3',
              'On **Design Inputs**, read the first group',
              '**Heating Steam Flow** in **T/h** (starts at `0.79`) and a **With Thermo Vapor Compressor (TVC)** switch, off',
            ],
            [
              '4',
              'Read the seawater group',
              '**Seawater Temperature** °C (`30`), **Seawater Salinity** ppm (`35000`), **Max Brine Salinity** ppm (`65000`), **Condenser Approach** °C (`4`), **SW Outlet Temp (absolute)** °C (blank)',
            ],
            [
              '5',
              'Read the configuration group',
              '**Number of Effects** (`6`) and a row of per-effect preheater toggles',
            ],
            [
              '6',
              'Set **Heating Steam Flow** to `2.5` T/h and **Number of Effects** to `8`',
              'The results panel lower down recalculates by itself — there is no Calculate button',
            ],
            [
              '7',
              'Read the headline results panel',
              '**GOR**, **Distillate Output** in m³/day, **Total Distillate** in T/h',
            ],
            [
              '8',
              'Sanity-check the GOR',
              'For 8 effects with no TVC, a GOR around 7–8 is right. A GOR above the number of effects, or below 2, is wrong',
            ],
            [
              '9',
              'Sanity-check the distillate',
              'Total Distillate ≈ steam flow × GOR. With 2.5 T/h in and a GOR near 7.5 you expect around 18–19 T/h, i.e. roughly 450 m³/day',
            ],
            [
              '10',
              '**Double** the Heating Steam Flow to `5.0`',
              'The distillate output roughly doubles; the GOR barely moves. That is the correct behaviour',
            ],
            [
              '11',
              'Set it back to `2.5`. Turn on **With Thermo Vapor Compressor (TVC)**',
              'The first field renames itself to **Motive Steam Flow**, and **Motive Steam Pressure** (bar abs), **Superheat** (°C), **Top Brine Temperature** (°C) and **Entrained from Effect** appear',
            ],
            [
              '12',
              'Leave TVC on, set **Motive Steam Pressure** `10` bar abs, **Top Brine Temperature** `65` °C',
              'The GOR rises noticeably compared with the no-TVC case — that is what a TVC is for',
            ],
            [
              '13',
              'Turn TVC back off',
              'The extra fields disappear and the GOR returns to where it was',
            ],
            [
              '14',
              'Turn on the preheater toggle for two of the later effects, and set **Default Temp Rise per PH** to `4` °C',
              'The GOR improves slightly. Helper text explains later effects improve GOR more',
            ],
            [
              '15',
              'Open **Advanced Parameters**',
              '**Tube Material**, **Design Margin** %, **Fouling Resistance**, **BPE Safety Factor**, an **Include brine recirculation** switch, **Vacuum System**, **Anti-scalant Dose** mg/L, **Shells per Effect**',
            ],
            [
              '16',
              'Change **Tube Material**, **Design Margin** to `20`, **BPE Safety Factor** to `1.15`, **Anti-scalant Dose** to `3`',
              'Results move; nothing errors',
            ],
            [
              '17',
              'Set **Vacuum System** to an LRVP option',
              '**Seal Water Temperature**, a **Closed-loop seal water** switch and **Chiller COP** appear',
            ],
            [
              '18',
              '**Write down every input on this step**, including the advanced ones and which preheaters are on',
              'You will need all of them in Part C',
            ],
            ['19', 'Click **Proceed to Equipment & Geometry**', 'Step 2 opens'],
          ],
        },
        {
          k: 'h',
          text: 'Part B — geometry, detailed design and the wetting rate',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '20',
              'Read the **Equipment Geometry** controls',
              'A **Mode** dropdown with **Fixed Tube Count**, **Fixed Tube Length**, **Uniform Geometry**, and a value box that renames itself to suit',
            ],
            [
              '21',
              'Read the per-effect table columns',
              'Effect, Tubes, Tube L (m), Shell ID (mm), Inst. Area (m²), Margin, Spray (T/h), Recirc (T/h), **Γ (kg/m·s)**, Rows',
            ],
            [
              '22',
              'Look at the **Γ (kg/m·s)** column on every effect',
              'Every value should sit comfortably above **0.03 kg/(m·s)** — that is the validated project minimum wetting rate',
            ],
            [
              '23',
              '**If any Γ is shown in red or bold, note the value and the threshold the app appears to be using**',
              'If the app is flagging a design against a threshold **much smaller** than 0.03 kg/(m·s), that is a real finding — report it with the numbers',
            ],
            [
              '24',
              'Check the **Margin** column',
              'Every effect should show a positive margin, in green. A negative margin in red means the geometry you chose is undersized',
            ],
            [
              '25',
              'Set **Mode** to **Fixed Tube Length** and reduce the tube length substantially',
              'Tube counts rise, shell IDs change, and Γ moves. Follow it — a shorter tube with the same spray means a **higher** Γ',
            ],
            [
              '26',
              'Set **Mode** to **Uniform Geometry**, choose **Input → Tubes** and set **Overdesign Margin** to `15` %',
              'Every effect ends up with the same geometry, and the margin column stays positive throughout',
            ],
            [
              '27',
              'Sanity-check the shell diameters',
              'A warning marker appears against any shell under 1800 mm. Judge whether the sizes suit the plant you described',
            ],
            [
              '28',
              'Note your final Mode, value and margin, then click **Proceed to Detailed Design**',
              'Step 3 opens',
            ],
            [
              '29',
              'Read through Step 3',
              'Effect-by-effect detail, an auxiliary equipment section and, if you enabled it, a turndown table with a **Load** column and a **Wetting OK** column',
            ],
            [
              '30',
              'Check the **Wetting OK** column, if shown',
              'A tick or a cross per load point, and a stated **Minimum stable load** percentage. A minimum stable load above about 60 % is worth questioning',
            ],
            [
              '31',
              'Click through to **Review & Export**',
              'Step 4 opens, headed **Step 4 — Bill of Materials & Export**, with tabs **Equipment**, **Instruments**, **Valves**, **Summary**, each showing a count',
            ],
            [
              '32',
              '**Write down the headline results:** GOR, Distillate Output, total heat transfer area, the per-effect tube counts and shell IDs, and the equipment/instrument/valve counts',
              'You need these for Part C',
            ],
          ],
        },
        {
          k: 'h',
          text: 'Part C — save, start over, reload, and compare',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '33',
              'Click **Save** at the top right',
              'A dialog titled **Save Calculation** with a **Name** box',
            ],
            [
              '34',
              'Name it `UAT MED 8-effect` and click **Save**',
              'The dialog closes with no error',
            ],
            [
              '35',
              'Click **Start Over**',
              'The wizard returns to step 1 with the factory defaults — 0.79 T/h, 6 effects, no preheaters, no TVC',
            ],
            [
              '36',
              'Confirm the reset really is a reset',
              'Advanced Parameters are back to their defaults too, not left on your values',
            ],
            [
              '37',
              'Click **Load**',
              'A dialog titled **Load Saved Calculation** listing `UAT MED 8-effect` with the date you saved it',
            ],
            ['38', 'Click the saved case', 'The dialog closes and the wizard fills in'],
            [
              '39',
              '**Compare every step-1 input against your notes from step 18**',
              'Steam flow, effects, seawater temperature and salinity, max brine salinity, condenser approach, SW outlet temp, the TVC switch and all its fields, which preheaters are on and the temp rise, tube material, design margin, fouling resistance, BPE safety factor, brine recirculation, vacuum system, seal water settings, anti-scalant dose, shells per effect — **all identical**',
            ],
            [
              '40',
              'Go to step 2 and compare against your notes from step 28',
              'Mode, value and overdesign margin all identical',
            ],
            [
              '41',
              '**Compare every headline result against your notes from step 32**',
              'GOR, distillate, areas, per-effect tube counts and shell IDs, and the three BOM counts — **all identical, to the last digit**',
            ],
            ['42', 'Look particularly at the **Γ** column', 'Same values as before the save'],
            [
              '43',
              'Reload the whole browser page, then **Load** the case again',
              'Same result a second time',
            ],
            [
              '44',
              'Save a **second** case with different inputs, then load the **first** one back',
              "You get the first case's inputs, not a mixture of the two",
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Also check',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Any input you leave blank must come back blank after a reload, not filled with a default.',
            'The results panel recomputes as you type throughout. If you ever have to click something to make numbers appear, note where.',
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Reaching **Proceed to Detailed Design** before the geometry has actually computed — the button must stay disabled.',
          ],
        },
      ],
    },
    {
      id: 'UAT-THRM-03',
      title: 'MED Plant Designer outputs — reports and the hand-off to Estimation',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'produce each of the three MED reports, export the bill of materials, and confirm the hand-off into the Estimation module lands correctly.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone signed in; step 8 onwards also needs access to Estimation.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'requires the saved case `UAT MED 8-effect` from UAT-THRM-02. Load it and go to **Review & Export**.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'On **Review & Export**, click through the **Equipment**, **Instruments** and **Valves** tabs',
              'Each lists real items with tags, and the count in the tab heading matches the number of rows',
            ],
            ['2', 'Read the **Summary** tab', 'Totals that are consistent with the three lists'],
            [
              '3',
              'Click **Export All BOM (CSV)**',
              'A file downloads. Open it and confirm the same equipment, instruments and valves, with the same tags',
            ],
            [
              '4',
              'Open the report dialog (**Generate MED Design Report**) and choose **Brief (Proposal)**',
              'The description says it shows key performance and dimensions only, and does **not** reveal tube counts or HTCs',
            ],
            [
              '5',
              'Fill **Document Number**, **Revision**, **Project Name**, **Notes**, then click **Download PDF**',
              'A PDF downloads',
            ],
            [
              '6',
              'Open the brief PDF',
              'Your document number, revision and project name are on it; the GOR and distillate match the screen; **no tube counts or HTCs appear** — this one goes to customers',
            ],
            [
              '7',
              'Repeat with **Detailed (Engineering)**',
              'A much longer PDF with effect-by-effect design, U-values, a weight breakdown and the equipment list',
            ],
            [
              '8',
              'Repeat with **Verification**',
              'A PDF with property data, the temperature cascade, heat and mass balance, HTC breakdown, correlations and references',
            ],
            [
              '9',
              'In the verification PDF, find the **Wetting Rate Analysis** section',
              'A per-effect Γ table and a stated minimum wetting rate in kg/m·s. Check it against the **0.03 kg/(m·s)** project standard — if the report states a threshold far below that, report it',
            ],
            [
              '10',
              'Cross-check the three PDFs against each other',
              'GOR, distillate and total area agree across all three. A number that differs between reports is a serious finding',
            ],
            [
              '11',
              'Cross-check the PDFs against the screen',
              'Same numbers as step 41 of UAT-THRM-02',
            ],
            [
              '12',
              'Click **Export to Estimation BOM**',
              'A dialog titled **Export to Estimation BOM** showing each designed item and what it maps to in the catalogue, with anything unmatched marked **Not mapped (exports unpriced)**',
            ],
            [
              '13',
              'Note which items are unmapped, then complete the export',
              'You are told it succeeded',
            ],
            [
              '14',
              'Go to the **Estimation** module and open the BOM you exported into',
              'The equipment, instruments and valves from the designer are there, with the same tags and quantities',
            ],
            [
              '15',
              'Check the items that were flagged **Not mapped**',
              'They appear in the BOM with no price rather than being silently dropped',
            ],
            ['16', "Compare the BOM item count against the designer's tab counts", 'They agree'],
          ],
        },
      ],
    },
    {
      id: 'UAT-THRM-04',
      title: 'Flash Chamber Calculator end to end',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'size a flash chamber, sanity-check the balance and the sizing, save and reload the case, and produce a datasheet.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone signed in.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'nothing. Note your input values as you go.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Hub → **Plant Design** → **Flash Chamber**',
              'A page headed **Flash Chamber Calculator**, with buttons **Reset to Defaults**, **Save**, **Load** and **Generate Datasheet**',
            ],
            [
              '2',
              'Read the input panel on the left',
              'A box headed **Inputs** with four tabs: **Process**, **Chamber**, **Elevations**, **Nozzles**',
            ],
            [
              '3',
              'On **Process**, set **Water Type**, **Calculation Mode**, **Flow Rate Unit**, then **Water Flow Rate**',
              'The results on the right recalculate by themselves after a moment — there is no Calculate button',
            ],
            [
              '4',
              'Set **Operating Pressure**, **Flashing Temperature** and **Inlet Temperature**',
              'Note the pressure unit shown and use it. Results update',
            ],
            ['5', 'Set **Seawater Salinity**', 'Results update'],
            [
              '6',
              'Read the **Heat & Mass Balance** panel',
              'A table with **Stream** and **Flow Rate** columns and three rows — the inlet, the vapour and the brine',
            ],
            [
              '7',
              '**Check the mass balance yourself**',
              'Vapour flow + brine flow = inlet flow, to within rounding. If it does not close, that is the finding',
            ],
            [
              '8',
              '**Check the flash fraction is plausible**',
              'Flashing 10 °C off seawater releases roughly 1.5–2 % of the flow as vapour. A double-digit percentage from a small temperature drop is wrong',
            ],
            [
              '9',
              'Read the **Chamber Sizing** panel',
              'A diameter in mm, a vapour velocity in m/s with a status marker, and a vapour loading figure',
            ],
            [
              '10',
              'On the **Chamber** tab, change the demister selection',
              'The Souders-Brown factor changes and the required diameter moves with it — a vane pack should allow a smaller vessel than open space',
            ],
            [
              '11',
              'Set **Retention Time**, **Flashing Zone Height** and **Spray Angle**',
              'The chamber height changes sensibly — a wider spray angle should shorten the spray zone',
            ],
            [
              '12',
              '**Double the Water Flow Rate**',
              'Vapour flow roughly doubles; the chamber diameter grows by roughly 40 %, not 100 %. Area scales with flow, diameter with its square root',
            ],
            [
              '13',
              'Set the flow back. Go to **Nozzles** and set **Inlet Water Velocity**, **Outlet Brine Velocity**, **Vapor Outlet Velocity**',
              'The **Nozzle Sizing** panel updates',
            ],
            [
              '14',
              'Read the vapour outlet nozzle result',
              'Hover the help marker beside **Vapor Outlet Velocity** — it states the sonic velocity and the maximum recommended (35 % of sonic) at your saturation temperature. Confirm your chosen velocity is below it',
            ],
            [
              '15',
              'Go to **Elevations** and set **Pump Centerline Above FFL**, **Operating Level Above Pump**, **Operating Level Ratio**, **BTL Gap Below LG-L**',
              'The **NPSHa Calculation (Three Levels)** panel and the **Elevation Diagram** both update',
            ],
            [
              '16',
              'Read the NPSHa panel',
              'Three NPSHa figures for three liquid levels. Sanity-check: the **lowest** level must give the **smallest** NPSHa',
            ],
            [
              '17',
              'Reduce **Operating Level Above Pump** until NPSHa goes negative or the panel warns',
              'A warning appears rather than a silently impossible design',
            ],
            [
              '18',
              'Set it back to a sensible value. Look at the top of the results column',
              'If there are warnings, they appear as a yellow list. Read them and judge whether they make sense',
            ],
            [
              '19',
              '**Write down every input across all four tabs**',
              'You need them for the reload check',
            ],
            [
              '20',
              'Click **Save**, name it `UAT Flash Chamber 01`, click **Save**',
              'The dialog closes with no error',
            ],
            [
              '21',
              'Click **Reset to Defaults**',
              'Every tab returns to its starting values and the results change accordingly',
            ],
            ['22', 'Click **Load** and pick `UAT Flash Chamber 01`', 'The case reloads'],
            [
              '23',
              '**Compare all four tabs against your notes**',
              'Every input identical, including the ones on tabs you are not currently looking at',
            ],
            [
              '24',
              'Compare the results',
              'Balance, chamber diameter, nozzle sizes and all three NPSHa figures identical to before the save',
            ],
            [
              '25',
              'Look at the browser address bar',
              'It carries your inputs. Copy the whole address, open it in a new tab',
            ],
            [
              '26',
              'Check the page that opens from that address',
              'The same inputs and the same results — the link is shareable',
            ],
            [
              '27',
              'Click **Generate Datasheet**',
              'A dialog headed **Generate Datasheet**, pre-filled with document number `FC-DS-001`, and a summary showing Chamber Diameter, Operating Pressure and Vapor Production',
            ],
            ['28', 'Check the three summary figures against the screen behind it', 'They match'],
            [
              '29',
              'Fill **Revision**, **Project Name** and **Notes**, click **Download PDF**',
              'A PDF downloads',
            ],
            [
              '30',
              'Open the datasheet',
              'Your document number, revision and project name; the balance, chamber sizing, nozzle sizing and NPSHa all matching the screen, each with its unit',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            'Clicking **Generate Datasheet** before there is a result — the button must stay disabled.',
          ],
        },
      ],
    },
    {
      id: 'UAT-THRM-05',
      title: 'Save, load and delete a calculation — and who can see it',
      knownIssue: false,
      blocks: [
        {
          k: 'note',
          text: 'Every calculator that offers Save uses the same mechanism. Test it thoroughly once here, then just spot-check it in the sweep.',
          warn: false,
        },
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm saved calculations are kept per calculator and per person, load back exactly, and can be deleted.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'you, plus a colleague with any signed-in account.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'nothing.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Open **Pipe Sizing** from the hub',
              'Buttons **Load Saved** and **Reset** near the title; once a result appears, **Save** and **Generate Report** at the bottom right',
            ],
            [
              '2',
              'Click **Load Saved** before saving anything',
              'A dialog titled **Load Saved Calculation** reading "No saved calculations yet."',
            ],
            [
              '3',
              'Close it. Set some distinctive inputs — flow `250` ton/hr, target velocity `1.8` m/s, temperature `45` °C',
              'A result appears',
            ],
            ['4', 'Click **Save**', 'A dialog titled **Save Calculation** with a **Name** box'],
            [
              '5',
              'Try to click **Save** with the name empty',
              'The button is disabled — a name is required',
            ],
            ['6', 'Name it `UAT Pipe A` and click **Save**', 'The dialog closes with no error'],
            ['7', 'Change the inputs to something else and save again as `UAT Pipe B`', 'Saved'],
            ['8', 'Click **Reset**', 'Inputs return to their defaults'],
            [
              '9',
              'Click **Load Saved**',
              'Both entries listed, **most recent first**, each with the date it was saved',
            ],
            [
              '10',
              'Pick `UAT Pipe A`',
              'The dialog closes and **every** input comes back exactly as you set it — flow, unit, velocity, temperature, mode',
            ],
            [
              '11',
              'Check the result',
              'The same pipe size and actual velocity as when you saved it',
            ],
            [
              '12',
              'Load `UAT Pipe B`, then `UAT Pipe A` again',
              'Each load replaces the previous inputs completely — no leftovers from the other case',
            ],
            [
              '13',
              'Now open a **different** calculator — **Pump Sizing** — and click **Load Saved**',
              'Your pipe-sizing entries are **not** listed. Each calculator keeps its own set',
            ],
            [
              '14',
              'Save something in Pump Sizing, then go back to Pipe Sizing and open **Load Saved**',
              'Only the two pipe entries — the pump one does not leak across',
            ],
            [
              '15',
              'In the load list, click the bin icon next to `UAT Pipe B`',
              'It disappears **immediately, with no confirmation**. Note this in the Notes column — it is easy to lose a case by mis-clicking',
            ],
            [
              '16',
              'Close and reopen **Load Saved**',
              '`UAT Pipe B` is gone for good; `UAT Pipe A` is still there',
            ],
            ['17', 'Reload the browser and open **Load Saved** again', '`UAT Pipe A` survives'],
            [
              '18',
              'Have your **colleague** open Pipe Sizing on their own sign-in and click **Load Saved**',
              'They see **their own** saved cases only — none of yours. Saved calculations are private to the person who made them',
            ],
            [
              '19',
              'Have them save one, then check your own list again',
              'Theirs does not appear in yours',
            ],
            [
              '20',
              'Save a case with a name that already exists',
              'Note whether you end up with two entries of the same name or the first is replaced',
            ],
          ],
        },
        {
          k: 'meta',
          label: 'Should NOT be possible',
          text: '',
        },
        {
          k: 'ul',
          items: [
            "Seeing, loading or deleting another person's saved calculation.",
            "A calculation saved in one calculator turning up in another calculator's list.",
          ],
        },
      ],
    },
    {
      id: 'UAT-THRM-06',
      title: 'Calculator sweep — every remaining calculator, one row each',
      knownIssue: false,
      blocks: [
        {
          k: 'note',
          text: 'Do not rush this. For each row: open the calculator, type the inputs, and then judge the answer as an engineer — the units on screen, the magnitude, and how it moves when you change something. A number that appears without erroring is **not** a pass.',
          warn: false,
        },
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm every remaining calculator opens, computes, shows its units, and responds sensibly to a change of input.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone signed in.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'all of these are reached from **SALES & ESTIMATION → Thermal Calculators**. None has a Calculate button — results update as you type, so give each one a second to settle. The one exception is noted in its row.',
        },
        {
          k: 'p',
          text: '**For every row, check all four of these before ticking Pass:**',
        },
        {
          k: 'ul',
          items: [
            '**Units** — every result carries a unit, and it is the unit the label promises.',
            '**Magnitude** — the answer is plausible for the plant you described.',
            '**Response** — when you double the input named in the Check column, the result moves in the direction and by roughly the amount stated.',
            '**No blanks or errors** — nothing shows a dash, `NaN`, an empty box, or a red error for a perfectly reasonable input.',
          ],
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Calculator (hub section)', 'Type these inputs', 'Check'],
          rows: [
            [
              '1',
              '**MED Process Calculator** (Plant Design)',
              'Steam Flow `790` kg/hr, Steam Temperature `57` °C, Number of Effects `6`, Inlet Temperature `30` °C, Salinity `35000` ppm',
              'GOR (no unit), Net Distillate kg/hr, Output m³/day, Specific Energy kWh/m³. GOR should be near but below 6. Double the steam flow → distillate roughly doubles, GOR barely moves. Tick **With Thermo Vapor Compressor (TVC)** → the first two labels rename and GOR rises',
            ],
            [
              '2',
              '**Performance Ratio / GOR** (Plant Design)',
              'Number of Effects `6`, Top Brine Temperature `65` °C, Last Effect Temperature `40` °C, Steam Pressure `2.5` bar abs, Feed Salinity `35000` ppm',
              'Big **GOR** figure with a **Typical / Below typical / Above typical** chip, **STE (kWh/m³)**, **Thermal Efficiency** %. Raise the effects to 12 → GOR rises and STE falls. GOR above the number of effects is wrong',
            ],
            [
              '3',
              '**Thermo Vapour Compressor** (Compression)',
              'Mode **Specify Entrained**; Motive Steam Pressure `10` bar abs, Suction Vapor Pressure `0.1` bar abs, Discharge Pressure `0.3` bar abs, Entrained Vapor Flow `2` ton/hr',
              '**Entrainment Ratio** (no unit, typically 0.3–1.5), **Compression Ratio** (Pc/Ps = 3 here), **Expansion Ratio** (Pm/Ps = 100 here). Check both ratios by hand. Switch to **Specify Motive** → the flow label changes and the ratios hold',
            ],
            [
              '4',
              '**Mechanical Vapour Compressor** (Compression)',
              'Suction Pressure `0.1` bar abs, Discharge Pressure `0.2` bar abs, Vapor Flow Rate `5` ton/hr, Isentropic Efficiency `75` %, Mechanical Efficiency `95` %',
              '**Shaft Power** kW, **Compression Ratio** (= 2 here). Double the vapour flow → shaft power roughly doubles. Drop isentropic efficiency to 50 % → power rises',
            ],
            [
              '5',
              '**Heat Exchanger Calculator** (Heat Exchange)',
              '**Quick Calc → Sensible**: Mass Flow `100` ton/hr, Inlet `25` °C, Outlet `40` °C, Salinity `35000` ppm',
              '**Heat Duty** kW. Check by hand: 100 t/h ≈ 27.8 kg/s × ~3.99 kJ/kg·K × 15 K ≈ **1660 kW**. Then try the **LMTD** and **Latent** sub-tabs, and the **Full Design** tab — that one has an explicit **Run Design** button and returns **Required Area** m², **Tube Count**, **Shell ID** mm',
            ],
            [
              '6',
              '**Falling Film Evaporator** (Heat Exchange)',
              'Feed Flow `10` kg/s, Feed Temperature `60` °C, Steam Temperature `70` °C, Feed Salinity `35000` ppm, Tube OD `25.4`, Number of Tubes `500`',
              '**Overall HTC** W/(m²·K) — should land in the low thousands for falling film, **Wetting Ratio**, **Heat Duty** kW, **Evaporation Rate** kg/s. Evaporation rate must be a small fraction of feed flow. Halve the tube count → wetting ratio rises',
            ],
            [
              '7',
              '**Single Tube Analysis** (Heat Exchange)',
              'Vapour Temperature `70` °C, Vapour Flow `0.01` kg/s, Spray Flow per tube `0.05` kg/s, Tube OD `25.4` mm, Tube Length `3` m',
              '**Heat Duty (per tube)** kW — a single 3 m tube should give single-digit kW, not hundreds. Double the tube length → duty roughly doubles',
            ],
            [
              '8',
              '**Custom Tube Bundle** (Heat Exchange)',
              'Shape **Full Circle**, Shell Inner Diameter `2338` mm, Tube OD `25.4` mm, Pitch `33.4` mm, Tube Length `3` m',
              '**Total Tubes**. Sanity-check: a 2338 mm circle on 33.4 mm triangular pitch holds several thousand tubes. Switch to **Half Circle (Left)** → roughly half. Switch to **Rectangle** and enter a width and height → count changes accordingly',
            ],
            [
              '9',
              '**Lateral Tube Bundle** (Heat Exchange)',
              'Shell Inner Diameter `2338` mm, Tube OD `25.4` mm, Triangular Pitch `33.4` mm, Number of Lanes `4`, Lane Width `60` mm',
              '**Total Tubes** — must be **fewer** than the half-circle count from row 8, because the vapour lanes remove tubes. Raise Number of Lanes to 8 → the count falls further',
            ],
            [
              '10',
              '**Central Tube Bundle** (Heat Exchange)',
              'Shell Inner Diameter `2338` mm, Bundle Width `1500` mm, Bundle Height `1200` mm, Tube OD `25.4` mm, Pitch `33.4` mm',
              '**Total Tubes**. Before entering width and height it should say "Enter bundle width and height to see results." Double the bundle width → tube count roughly doubles. A bundle bigger than the shell should be refused or warned about',
            ],
            [
              '11',
              '**Desuperheating** (Heat Exchange)',
              'Steam Pressure `10` bar abs, Inlet Steam Temperature `300` °C, Target Outlet Temperature `190` °C, Steam Flow `5` ton/hr, Spray Water Temperature `30` °C',
              '**Required Spray Water Flow** ton/hr — should be a modest fraction of the steam flow, well under 1 t/h here. Also shown: **Tsat** °C (≈180 °C at 10 bar) and **Inlet Superheat** °C (≈120 K). Set the target below Tsat → it should refuse or warn',
            ],
            [
              '12',
              '**Thermal Expansion** (Heat Exchange)',
              'Mode **Free Expansion**; Initial Length `1000` mm, Installation Temperature `20` °C, Operating Temperature `120` °C, Material carbon steel',
              '**Free Thermal Expansion ΔL** — about **1.2 mm** for 1 m of carbon steel over 100 K. Switch to **Fully Restrained** → **Restrained Thermal Stress σ** in MPa, of order 200–250 MPa. Change material to aluminium → ΔL roughly doubles',
            ],
            [
              '13',
              '**Fouling & Scaling Prediction** (Heat Exchange)',
              'Feed Salinity `35000` ppm, Calcium `420`, pH `8.1`, Temperature Max `75`, Concentration Factor `1.5`',
              '**Max TBT (no antiscalant)** °C, **Max TBT (with antiscalant)** °C, **Dominant Scalant**. The with-antiscalant TBT must be the **higher** of the two. Raise the concentration factor to 2.5 → both max TBTs fall',
            ],
            [
              '14',
              '**Pipe Sizing** (Fluid Systems)',
              'Mode **Size by Flow**; Flow Rate `100` ton/hr, Target Velocity `1.5` m/s, Temperature `40` °C',
              'A headline pipe size like `6" Sch 40` with a status chip, plus **Actual Velocity** m/s and **Inner Diameter** mm. Actual velocity must be near but not above the target. Double the flow → the size steps up. Switch to **Check Velocity**, pick a size, and confirm the velocity it reports',
            ],
            [
              '15',
              '**Pressure Drop** (Fluid Systems)',
              'Pipe Size `4`, Pipe Length `100` m, Mass Flow `50` ton/hr, Pipe Roughness `0.045` mm, Elevation Change `0` m',
              '**Total Pressure Drop** in m H₂O and **Velocity** m/s. Double the length → drop roughly doubles. Double the flow → drop roughly **quadruples** (it goes with the square). Add a few fittings → the drop increases',
            ],
            [
              '16',
              '**Pump Sizing** (Fluid Systems)',
              'Mass Flow `100` ton/hr, Static Head `20` m, Fluid Density `1025` kg/m³, Pump Efficiency `70` %, Motor Efficiency `95` %',
              '**Total Differential Head** m, **Hydraulic** kW, **Brake (Shaft)** kW. Brake power must exceed hydraulic power. Check by hand: 100 t/h at 20 m ≈ 5.6 kW hydraulic, so ~8 kW brake. Drop pump efficiency to 50 % → brake power rises, hydraulic does not',
            ],
            [
              '17',
              '**Suction System Designer** (Fluid Systems)',
              'Mode **Calculate Required Elevation**; Effect Pressure `300` mbar(a), Mass Flow `100` ton/hr, Pump NPSHr `3.0` m, Safety Margin `0.5` m',
              '**Required Minimum Elevation (Nozzle to Pump CL)** m — should exceed NPSHr + margin. Switch to **Verify Provided Elevation**, enter `5.0` m, and read **Elevation is Adequate** or **Elevation is Insufficient**. Enter an elevation well below the required figure → it must say insufficient',
            ],
            [
              '18',
              '**Siphon Sizing** (Fluid Systems)',
              'Upstream `300` mbar, Downstream `250` mbar, Mass Flow `100` ton/hr, Target Velocity `1.0` m/s, Safety Factor `20` %',
              'A headline pipe size, **Min. Siphon Height** m, **Velocity** m/s. The U-bend height must exceed the 50 mbar difference expressed as a water column (~0.5 m). Widen the pressure gap to 100 mbar → the height grows',
            ],
            [
              '19',
              '**Siphon Sizing — Batch Mode** (Fluid Systems)',
              'From Siphon Sizing click **Batch Mode (All Effects)**',
              'A page headed **Batch Siphon Sizing** that sizes several inter-effect siphons at once. Enter a set of effects and confirm each row matches what the single calculator gives for the same conditions',
            ],
            [
              '20',
              '**Demister Sizing** (Fluid Systems)',
              '**Steam / Sat. Water (auto-lookup)** + **By Pressure**; Saturation Pressure `0.08` bar a, Vapor Mass Flow `1.5` kg/s, Design Margin `80` %, demister type **Standard Wire Mesh**',
              '**K Factor** m/s and **Design Velocity** m/s, plus **Required demister area** m² and **Min. vessel diameter** m. Switch to **Vane / Chevron Pack** → K factor rises and the required diameter falls. Double the vapour flow → area roughly doubles',
            ],
            [
              '21',
              '**Strainer Sizing** (Fluid Systems)',
              'Volumetric Flow `100` m³/hr, Line Size (NPS) `4`, Strainer Type **Y-type**, Mesh Size left blank, Fluid Density `1025` kg/m³',
              '**Recommended Mesh Size** mm, a **Total** pressure loss and an **Open Area (Clean)**. Then pick a mesh yourself — the label should change to **Selected Mesh Size**. A finer mesh must give a higher pressure loss. Compare the clean and 50 %-clogged losses',
            ],
            [
              '22',
              '**Strainer Sizing — Batch Mode** (Fluid Systems)',
              'From Strainer Sizing click **Batch Mode**',
              'A page headed **Batch Strainer Sizing**. Enter a set of lines and confirm one of the rows matches the single calculator for the same inputs',
            ],
            [
              '23',
              '**Vacuum System Design** (Plant Auxiliaries)',
              'Mode **2-Stage Ejector**; Suction Pressure `70` mbar abs, Coolant Inlet Temperature `28` °C, Dry NCG Flow `5`, Motive Steam Pressure `8`, Design Margin `10`',
              '**Suction** mbar, **Dry NCG** kg/h, **Motive Steam** kg/h, **LRVP Power** kW. Switch through **Single Ejector**, **LRVP Only** and **Hybrid** — the equipment listed changes and steam consumption should be lowest on LRVP Only. Halve the suction pressure → motive steam rises sharply',
            ],
            [
              '24',
              '**Vacuum Breaker Sizing** (Plant Auxiliaries)',
              'Mode **Manual Valve — Size for Target Time**; Total Volume `200` m³, Lowest Operating Vacuum Pressure `50` mbar abs, Number of Vacuum Breakers `2`, Equalization Time `60` min, Ambient Air Temperature `35` °C',
              '**Selected Size (N identical valves)** as `DN nn` with the NPS beside it, plus **Vol. per Breaker** m³ (= 100 here). Halve the equalization time → the valve gets bigger. Try both **Burst Diaphragm** modes and confirm they compute',
            ],
            [
              '25',
              '**Chemical Dosing & CIP** (Plant Auxiliaries)',
              '**Chemical Dosing** tab: Feed Seawater Flow `500` m³/h, Dose `2` mg/L, Solution Density `1.10` kg/L, Storage Days `30`',
              '**Dosing Flow** (mL/min or L/h), **Daily** kg/day, **Annual** kg/yr. Check by hand: 500 m³/h × 2 mg/L = 1 kg/h = **24 kg/day**. Double the dose → everything doubles. Then use the **Acid CIP** tab and confirm **System Volume** and **Annual Acid** compute',
            ],
            [
              '26',
              '**Spray Nozzle Selection** (Plant Auxiliaries)',
              'Mode **Nozzle Selection**, category **Full Cone — Circular**; Total Required Flow (choose the unit), Operating Pressure `3` bar, Number of Nozzles `10`, Flow Tolerance `25` %',
              '**Required Flow (total)**, **Flow per Nozzle**, **Pressure** bar, and a **Matches** count of real catalogue nozzles. Flow per nozzle × 10 must equal the total. Set an absurd flow → it should report no matches rather than an error. Then try **Bundle Layout** with a bundle length and width and confirm **Layout**, **Coverage** mm and **Pitch** mm',
            ],
            [
              '27',
              '**Steam Tables** (Properties)',
              '**Saturation** + **Temperature**; Temperature `100` °C',
              '**Saturation Pressure** ≈ **1.013 bar** — this is the one you can check against memory. Switch to **Pressure** and enter `1.013` bar (absolute) → **Saturation Temperature** ≈ 100 °C. Change the unit selector to mbar and kg/cm² (gauge) and confirm the number converts correctly. Try the **Subcooled** and **Superheated** modes',
            ],
            [
              '28',
              '**Seawater Properties** (Properties)',
              'Temperature `40` °C, Salinity `35000` ppm',
              '**Density (ρ)** ≈ **1022 kg/m³**, **Boiling Point Elevation (BPE)** ≈ 0.5–0.7 °C, **Specific Heat (Cp)** ≈ 4.0 kJ/(kg·K). Double the salinity → density and BPE rise, Cp falls. Change the unit to **g/kg (‰)** and enter `35` → identical results',
            ],
            [
              '29',
              '**NCG Properties** (Properties)',
              'Mode **NCG + Vapour**; Temperature `40` °C, NCG Partial Pressure `0.075`, Total (Wet) Gas Flow `50`',
              '**Total Pressure** bar abs, **NCG Partial P** bar, **Density** kg/m³. Total pressure must equal the NCG partial pressure plus the saturation pressure of water at 40 °C (≈0.0738 bar), so around 0.149 bar. Toggle the switch that reinterprets the pressure as a total and confirm the label changes to **Total System Pressure (abs)**. Try all four modes',
            ],
          ],
        },
        {
          k: 'p',
          text: '**Also check, across the whole sweep:**',
        },
        {
          k: 'ul',
          items: [
            "Every calculator's **Reset** puts it back to the state it opened in.",
            'Where a **Generate Report** button exists, produce one PDF and confirm the numbers on it match the screen and carry their units.',
            'Note in the Notes column any calculator that has **no Save button** — six of them do not (see Known issues).',
          ],
        },
      ],
    },
    {
      id: 'UAT-THRM-07',
      title: 'Reference Projects library',
      knownIssue: false,
      blocks: [
        {
          k: 'meta',
          label: 'Goal',
          text: 'confirm the as-built reference data is readable and usable for validating a calculator result.',
        },
        {
          k: 'meta',
          label: 'Who',
          text: 'anyone signed in.',
        },
        {
          k: 'meta',
          label: 'Before you start',
          text: 'nothing. This page is read-only — there is nothing to save and nothing to break.',
        },
        {
          k: 'table',
          steps: true,
          head: ['#', 'Do this', 'You should see'],
          rows: [
            [
              '1',
              'Hub → **Plant Design** → **Reference Projects**',
              'A page headed **Reference Projects**, explaining the data is as-built from real MED-TVC plants',
            ],
            [
              '2',
              'Read the notice under the heading',
              'It states the data was taken from original project datasheets and that values are as-built unless noted',
            ],
            ['3', 'Read the project cards', 'Three projects — Campiche, CADAFE and MORON'],
            [
              '4',
              'Open each project in turn',
              'Real design data with units — capacity, number of effects, temperatures, areas',
            ],
            [
              '5',
              'Find the **Cross-Project Comparison** section',
              'The three projects side by side on the same measures',
            ],
            [
              '6',
              'Look for anything editable — an Add, Edit, Delete or Save',
              'There is none. This is a read-only library',
            ],
            [
              '7',
              "Pick one project's inputs and put them through the **MED Process Calculator**",
              'The GOR and distillate you compute should be in the same neighbourhood as the as-built figures. A large gap is worth reporting, with both sets of numbers',
            ],
            [
              '8',
              'Do the same with the **Performance Ratio / GOR** calculator',
              'Again, a comparable answer',
            ],
          ],
        },
      ],
    },
  ],
  gaps: [
    {
      text: '**Six calculators have no Save or Load at all:** Steam Tables, Seawater Properties, Custom Tube Bundle, Lateral Tube Bundle, Central Tube Bundle and Thermal Expansion. Their inputs cannot be kept.',
    },
    {
      text: '**Condenser and Ejector are on the hub but marked Coming Soon.** They are placeholders, not working tools.',
    },
  ],
};

export default thermalGuide;
